import { act, cleanup, renderHook, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { useDeploymentQueueSettings } from '@/hooks/useDeploymentQueueSettings';
import type { DeploymentQueueSettings } from '@/lib/deploymentQueue';
import type { User } from '@/types';
const state = vi.hoisted(() => ({ member: { id: 'example-operator', isActive: true, role: 'member' } as User, toggle: true, ready: true, response: null as unknown, topics: [] as string[], read: vi.fn(), write: vi.fn() }));
vi.mock('@/context/AuthContext', () => ({ useAuthContext: () => ({ currentMember: state.member, realMemberId: state.member.id }) }));
vi.mock('@/context/UIContext', () => ({ useUIContext: () => ({ featureTogglesReady: state.ready, featureToggles: { deploymentQueue: state.toggle } }) }));
vi.mock('@/integrations/supabase/client', () => ({ supabase: {
  from: () => { let writing = false; const query = { select: () => query, eq: vi.fn(() => query), insert: (row: unknown) => { writing = true; state.write(row); return query; }, update: (row: unknown) => { writing = true; state.write(row); return query; }, single: async () => ({ data: { updated_at: 'revision-2' }, error: null as null }), maybeSingle: async () => { if (writing) return { data: { updated_at: 'revision-2' }, error: null }; state.read(); return state.response; } }; return query; },
  channel: (topic: string) => { state.topics.push(topic); const channel = { on: () => channel, subscribe: () => channel }; return channel; }, removeChannel: vi.fn(),
} }));
const config: DeploymentQueueSettings = { version: 1, enabled: true, taskStatusIds: ['example-wait'], operatorMemberIds: ['example-operator'] };
beforeEach(() => { state.member = { id: 'example-operator', isActive: true, role: 'member' } as User; state.toggle = true; state.ready = true; state.response = { data: { value: config, updated_at: 'revision-1' }, error: null }; state.read.mockReset(); state.write.mockReset(); state.topics = []; });
afterEach(cleanup);
describe('trusted deployment settings hook', () => {
  it('derives operators only from a successful read and both switches', async () => { const { result, rerender } = renderHook(useDeploymentQueueSettings); expect(result.current.isOperator).toBe(false); await waitFor(() => expect(result.current.status).toBe('ready')); expect(result.current.isOperator).toBe(true); state.toggle = false; rerender(); expect(result.current.isOperator).toBe(false); expect(result.current.config).toBeNull(); });
  it.each(['member', 'admin'] as const)('denies operator configuration by %s outside the form', async role => { state.member.role = role; const { result } = renderHook(useDeploymentQueueSettings); await waitFor(() => expect(result.current.status).toBe('ready')); await expect(result.current.save(config, 'revision-1')).rejects.toThrow('forbidden'); expect(state.write).not.toHaveBeenCalled(); });
  it('allows only a current super admin to save', async () => { state.member.role = 'super_admin'; const { result } = renderHook(useDeploymentQueueSettings); await waitFor(() => expect(result.current.status).toBe('ready')); await act(async () => { await result.current.save(config, 'revision-1'); }); expect(state.write).toHaveBeenCalledWith(expect.objectContaining({ key: 'deployment_queue', value: config, updated_by: 'example-operator' })); });
  it.each([{ data: null, error: { message: 'denied' } }, { data: { value: { ...config, enabled: 'true' } }, error: null }])('keeps failed or malformed configuration unknown: %j', async response => { state.response = response; const { result } = renderHook(useDeploymentQueueSettings); await waitFor(() => expect(result.current.status).toBe('error')); expect(result.current.config).toBeNull(); expect(result.current.isOperator).toBe(false); });
  it('keeps missing configuration absent without inventing defaults', async () => { state.response = { data: null, error: null }; const { result } = renderHook(useDeploymentQueueSettings); await waitFor(() => expect(result.current.status).toBe('missing')); expect(result.current.config).toBeNull(); expect(result.current.isOperator).toBe(false); });
  it('drops the old principal config immediately on a member switch', async () => { const { result, rerender } = renderHook(useDeploymentQueueSettings); await waitFor(() => expect(result.current.isOperator).toBe(true)); state.member = { ...state.member, id: 'example-other' }; rerender(); expect(result.current.isOperator).toBe(false); expect(result.current.config).toBeNull(); await waitFor(() => expect(result.current.status).toBe('ready')); expect(result.current.isOperator).toBe(false); });
  it('isolates simultaneous consumers so cleanup cannot detach another settings subscriber', async () => { const { result } = renderHook(() => ({ first: useDeploymentQueueSettings(), second: useDeploymentQueueSettings() })); await waitFor(() => expect(result.current.first.status).toBe('ready')); await waitFor(() => expect(result.current.second.status).toBe('ready')); expect(state.topics).toHaveLength(2); expect(new Set(state.topics).size).toBe(2); });
  it('does not read before capability readiness', () => { state.ready = false; const { result } = renderHook(useDeploymentQueueSettings); expect(result.current.status).toBe('loading'); expect(state.read).not.toHaveBeenCalled(); });
});
