import {describe,it,expect,vi} from 'vitest';
vi.mock('@/integrations/supabase/client',()=>({supabase:{},USING_MOCK_BACKEND:true}));
import {createQaClient} from '../lib/qa/client';import type {QaContext} from '../lib/qa/domain';
const context=(workspaceId:string):QaContext=>({workspaceId,actor:{id:'admin',role:'admin'},now:'2026-10-03T00:00:00.000Z',newId:()=>crypto.randomUUID(),memberIds:new Set(['admin','coord','reporter','next']),projectIds:new Set(['p']),taskIds:new Set()});
const request={type:'request_handoff' as const,reason:'Need response',nextOwnerId:'next',replyBy:null as null,externalDependency:''};
describe('QA Mock coordination parity',()=>{
 it('uses stored settings, never UI supplied coordinator scope',async()=>{const ctx=context('mock-coord-a'),client=createQaClient({enabled:()=>true,context:()=>ctx,mock:true});const issue=await client.create({projectId:'p',title:'Synthetic',actual:'Example',observedEnvironment:'Stage'});ctx.actor={id:'coord',role:'member',qaCoordinatorProjectIds:['p']};await expect(client.command(issue,request)).rejects.toThrow('qa_forbidden');ctx.actor={id:'admin',role:'admin'};await client.saveCoordination('p','coord',0,'save-coord-a');ctx.actor={id:'coord',role:'member'};expect((await client.command(issue,request)).handoff?.nextOwnerId).toBe('next');});
 it('retains command receipt and rejects changed payload reuse',async()=>{const ctx=context('mock-coord-b'),client=createQaClient({enabled:()=>true,context:()=>ctx,mock:true});const issue=await client.create({projectId:'p',title:'Synthetic',actual:'Example',observedEnvironment:'Stage'});const first=await client.command(issue,request,'same-command-b');expect(await client.command(issue,request,'same-command-b')).toEqual(first);await expect(client.command(issue,{...request,reason:'Changed'},'same-command-b')).rejects.toThrow('qa_command_id_reused');expect((await client.get(issue.id)).events).toHaveLength(2);});
 it('coordinator appointment CAS/replay is independent from Bug version',async()=>{const ctx=context('mock-coord-c'),client=createQaClient({enabled:()=>true,context:()=>ctx,mock:true});expect(await client.saveCoordination('p','coord',0,'same-config-c')).toMatchObject({version:1});expect(await client.saveCoordination('p','coord',0,'same-config-c')).toMatchObject({version:1});await expect(client.saveCoordination('p',null,0,'stale-config-c')).rejects.toThrow('qa_version_conflict');await expect(client.saveCoordination('p','next',0,'same-config-c')).rejects.toThrow('qa_command_id_reused');ctx.memberIds=new Set();await expect(client.getCoordination('p')).rejects.toThrow('qa_forbidden');});
});
