// @vitest-environment node
import {describe,it,expect,vi} from 'vitest';
vi.mock('@/integrations/supabase/client',()=>({supabase:{functions:{invoke:vi.fn()}},USING_MOCK_BACKEND:true}));
import {createReleaseClient} from '@/lib/releases/client';
import type {ReleaseContext} from '@/lib/releases/core';
let n=0;
const context=(workspaceId:string):ReleaseContext=>({workspaceId,actorId:'admin',role:'admin',now:'2026-10-03T00:00:00Z',newId:()=>`id-${++n}`,memberIds:new Set(['admin']),projectIds:new Set(['p']),taskProjects:new Map([['task','p']]),environments:['Stage'],qaSources:new Map()});
const manifest={title:'Example',ownerId:'admin',components:[{id:'component',name:'Server',projectId:'p',taskIds:['task'],targets:[{environment:'Stage',build:'v1',config:'same',data:'none'}]}]};
describe('release mock parity and isolation',()=>{
 it('does not mix events when two workspaces use the same batch id',async()=>{const a=createReleaseClient({context:()=>context('workspace-a'),mock:true}),b=createReleaseClient({context:()=>context('workspace-b'),mock:true});for(const client of[a,b])await client.execute({operation:'create',batchId:'same-id',expectedVersion:0,manifest});expect((await a.events('same-id')).events).toHaveLength(1);expect((await b.events('same-id')).events).toHaveLength(1);});
 it('keeps archived project history readable and permits historical rollback, while refusing new plans',async()=>{let ctx=context('workspace-archive');const client=createReleaseClient({context:()=>ctx,mock:true});let {batch}=await client.execute({operation:'create',batchId:'archived-release',expectedVersion:0,manifest});({batch}=await client.execute({operation:'start_attempt',batchId:batch.id,expectedVersion:batch.version,environment:'Stage',componentIds:['component'],note:'Observed start'}));({batch}=await client.execute({operation:'record_result',batchId:batch.id,expectedVersion:batch.version,attemptId:batch.attempts[0].id,type:'deployed',note:'Observed result',url:null}));ctx={...ctx,projectIds:new Set(),visibleProjectIds:new Set(['p'])};expect((await client.get(batch.id)).version).toBe(batch.version);await expect(client.execute({operation:'edit_manifest',batchId:batch.id,expectedVersion:batch.version,manifest})).rejects.toThrow('release_reference_unavailable');const rolled=await client.execute({operation:'record_result',batchId:batch.id,expectedVersion:batch.version,attemptId:batch.attempts[0].id,type:'rollback',note:'Observed restore',url:null});expect(rolled.batch.attempts[0].records.at(-1)?.type).toBe('rollback');});
 it('fails closed for ordinary browser publication even when the client is an administrator',async()=>{const client=createReleaseClient({context:()=>context('workspace-browser'),mock:true});const {batch}=await client.execute({operation:'create',batchId:'private-release',expectedVersion:0,manifest});await expect(client.execute({operation:'publish_thread',batchId:batch.id,expectedVersion:1,teamId:'TTEST',channelId:'CTEST',confirmed:true})).rejects.toThrow('release_forbidden');});
});
