// @vitest-environment node
import {describe,it,expect,vi} from 'vitest';
import {handleRelease} from '../../docker/volumes/functions/slack-interact/release-handler';
import {releaseDetail,releaseForm,releaseList,releaseSubmission,RELEASE_WORDS} from '../../docker/volumes/functions/slack-interact/release-ui';
import {createReleaseData} from '../../docker/volumes/functions/slack-interact/release-backend';
import {applyReleaseCommand,ReleaseError,type ReleaseBatch,type ReleaseContext} from '@/lib/releases/core';
import type {Actions} from '../../docker/volumes/functions/slack-interact/handler';
type Row=Record<string,any>;
let sequence=0;
const source={channel:'CTEST',team:'TTEST',user:'UADMIN',locale:'zh-TW'};
const actor={id:'admin',role:'admin',binding_id:'binding-test',jwt:'signed-member',locale:'zh-TW'};
const batch=():ReleaseBatch=>applyReleaseCommand(null,{operation:'create',commandId:'create-synthetic',batchId:'release-test',expectedVersion:0,manifest:{title:'Private <@U123> release',ownerId:'admin',components:[{id:'server',name:'Server',projectId:'p',taskIds:['t'],targets:[{environment:'Stage',build:'v1',config:'same',data:'none'}]}]}},{workspaceId:'default',actorId:'admin',role:'admin',now:'2026-10-03T00:00:00Z',newId:()=>`id-${++sequence}`,memberIds:new Set(['admin']),projectIds:new Set(['p']),taskProjects:new Map([['t','p']]),environments:['Stage'],qaSources:new Map()} satisfies ReleaseContext);
function harness(){const jobs:Promise<unknown>[]=[],b=batch();const request=vi.fn(async(_a:Row,p:Row):Promise<any>=>p.action==='get'?structuredClone(b):p.action==='list'?{batches:[b],page:0,hasMore:false}:p.action==='receipt'?{found:false}:{commandId:p.command.commandId,batch:b});
 const slack=vi.fn(async(method:string):Promise<Row>=>method==='conversations.members'?{members:['UADMIN']}:{view:{id:'view-open',hash:'new-hash'}}),reply=vi.fn(async()=>{});
 const d={enabled:vi.fn(async()=>true),actor:vi.fn(async()=>actor),slack,reply,background:(p:Promise<unknown>)=>jobs.push(p),search:vi.fn(async()=>[]),releases:{request,environments:vi.fn(async()=>['Stage']),tasks:vi.fn(async()=>[]),qaOptions:vi.fn(async()=>[])}} as unknown as Actions;
 return {d,b,jobs,request,slack,reply,done:()=>Promise.all(jobs)};
}
function submit(form='cancel',extra:Row={}){const id=`view-${++sequence}`;return {type:'view_submission',team:{id:'TTEST'},user:{id:'UADMIN'},view:{id,hash:'old-hash',callback_id:'livo_release_save',private_metadata:JSON.stringify({...source,form,commandId:`command-${++sequence}`,batchId:'release-test',version:1,actorId:'admin',bindingId:'binding-test',...extra}),blocks:[{type:'input',block_id:'note',label:{type:'plain_text',text:'Note'},element:{type:'plain_text_input',action_id:'value'}}],state:{values:{note:{value:{value:'private operator note'}}}}}};}
describe('release private Slack workflow',()=>{
 it('ACKs submissions before actor lookup or any database work finishes',async()=>{const h=harness();let resolve!:(value:Row)=>void;h.d.actor=vi.fn(()=>new Promise(r=>{resolve=r;}));const response=await handleRelease(submit(),h.d,source);expect(response?.response_action).toBe('update');expect(h.request).not.toHaveBeenCalled();resolve(actor);await h.done();expect(h.request).toHaveBeenCalledWith(actor,expect.objectContaining({action:'command'}));});
 it('rejects stale form versions instead of upgrading to the latest aggregate',async()=>{const h=harness();h.b.version=2;await handleRelease(submit(),h.d,source);await h.done();expect(h.request.mock.calls.some(([,p])=>p.action==='command')).toBe(false);expect(JSON.stringify(h.slack.mock.calls)).toContain('本次未儲存');});
 it('rechecks enabled/member on each page and never reuses private detail after access loss',async()=>{const h=harness();h.d.actor=vi.fn(async()=>{throw new ReleaseError('release_forbidden',403);});await handleRelease({type:'block_actions',team:{id:'TTEST'},user:{id:'UADMIN'},view:{id:'private-view',hash:'h'},actions:[{action_id:'livo_release_open',value:JSON.stringify({batchId:h.b.id})}]},h.d,source);await h.done();expect(h.request).not.toHaveBeenCalled();expect(JSON.stringify(h.slack.mock.calls)).not.toContain(h.b.title);expect(h.reply).not.toHaveBeenCalled();});
 it('retries an uncertain command in a fresh handler with the exact id, frozen version and complete fields',async()=>{const h=harness();let fail=true;h.request.mockImplementation(async(_a,p)=>{if(p.action==='receipt')return {found:false};if(p.action==='get')return h.b;if(fail)throw new ReleaseError('release_transport_error',503);return {batch:h.b,commandId:p.command.commandId};});const p=submit();const ack=await handleRelease(p,h.d,source);expect(ack?.view.blocks.find((b:Row)=>b.block_id==='note').element.initial_value).toBe('private operator note');await h.done();const frozen=(h.slack.mock.calls.at(-1) as unknown as [string,Row])[1].view;expect(frozen.callback_id).toBe('livo_release_save');expect(frozen.private_metadata.length).toBeLessThan(3000);fail=false;vi.resetModules();const fresh=(await import('../../docker/volumes/functions/slack-interact/release-handler')).handleRelease;await fresh({...p,view:{...frozen,id:p.view.id,hash:'retry-hash',state:p.view.state}},h.d,source);await h.done();const commands=h.request.mock.calls.filter(([,p])=>p.action==='command').map(([,p])=>p.command);expect(commands).toHaveLength(2);expect(commands[1]).toEqual(commands[0]);});
 it('recovers a successful but lost response through the own receipt before checking the changed aggregate',async()=>{const h=harness();let committed=false;h.request.mockImplementation(async(_a,p)=>{if(p.action==='receipt')return {found:committed};if(p.action==='get')return h.b;committed=true;h.b.version=2;throw new ReleaseError('release_transport_error',503);});const p=submit();await handleRelease(p,h.d,source);await h.done();const frozen=(h.slack.mock.calls.at(-1) as unknown as [string,Row])[1].view;vi.resetModules();const fresh=(await import('../../docker/volumes/functions/slack-interact/release-handler')).handleRelease;await fresh({...p,view:{...frozen,id:p.view.id,hash:'recovery',state:p.view.state}},h.d,source);await h.done();expect(h.request.mock.calls.filter(([,p])=>p.action==='command')).toHaveLength(1);expect(h.request.mock.calls.filter(([,p])=>p.action==='get')).toHaveLength(1);expect(JSON.stringify(h.slack.mock.calls.at(-1))).toContain('原操作已儲存');});
 it('does not imply modified fields were applied when the first ACK was lost',async()=>{const h=harness();h.request.mockImplementation(async(_a,p)=>p.action==='receipt'?{found:true}:h.b);const original=submit();original.view.state.values.note.value.value='An edit on the original unacknowledged form';await handleRelease(original,h.d,source);await h.done();expect(h.request.mock.calls.some(([,p])=>p.action==='command')).toBe(false);expect(JSON.stringify(h.slack.mock.calls.at(-1))).toContain('這次重送的內容沒有另行套用');});
 it('rejects editing frozen retry fields or using a newly rebound administrator',async()=>{const h=harness();h.request.mockImplementation(async(_a,p)=>p.action==='receipt'?{found:false}:p.action==='get'?h.b:Promise.reject(new ReleaseError('release_transport_error',503)));const p=submit();await handleRelease(p,h.d,source);await h.done();const frozen=(h.slack.mock.calls.at(-1) as unknown as [string,Row])[1].view,before=h.request.mock.calls.length;const changed={...p,view:{...frozen,id:p.view.id,hash:'changed',state:{values:{note:{value:{value:'Different intent'}}}}}};const reply=await handleRelease(changed,h.d,source);expect(JSON.stringify(reply)).toContain('其他內容');expect(h.request).toHaveBeenCalledTimes(before);h.d.actor=vi.fn(async()=>({...actor,id:'different-admin',binding_id:'new-binding'}));await handleRelease({...p,view:{...frozen,id:p.view.id,hash:'rebound',state:p.view.state}},h.d,source);await h.done();expect(h.request).toHaveBeenCalledTimes(before);});
 it('keeps successful receipts truthful if the private modal refresh fails',async()=>{const h=harness();h.slack.mockRejectedValue(new Error('view closed'));await handleRelease(submit(),h.d,source);await h.done();expect(h.reply).toHaveBeenCalledWith(expect.anything(),'已儲存發布紀錄。');expect(JSON.stringify(h.reply.mock.calls)).not.toContain('private operator note');});
 it('does not publish when the bound Slack actor left the destination channel',async()=>{const h=harness();h.slack.mockImplementation(async(method)=>method==='conversations.members'?{members:['UOTHER']}:{view:{id:'v'}});await handleRelease(submit('publish_thread',{teamId:'TTEST',channelId:'CTEST'}),h.d,source);await h.done();expect(h.request.mock.calls.some(([,p])=>p.action==='command')).toBe(false);});
 it('publishes only after channel membership and preserves the confirmed destination',async()=>{const h=harness();await handleRelease(submit('publish_thread',{teamId:'TTEST',channelId:'CTEST'}),h.d,source);await h.done();expect(h.slack).toHaveBeenCalledWith('conversations.members',expect.objectContaining({channel:'CTEST'}));expect(h.request).toHaveBeenCalledWith(actor,{action:'command',command:expect.objectContaining({operation:'publish_thread',teamId:'TTEST',channelId:'CTEST',confirmed:true,expectedVersion:1})});});
 it('renders user data only as plain text, paginates eight rows, and provides all three locales',()=>{const b=batch(),view=releaseDetail(b,source,'overview',0,undefined,true);expect(JSON.stringify(view)).not.toContain('mrkdwn');for(const block of view.blocks.filter((x:Row)=>x.type==='actions'))expect(new Set(block.elements.map((x:Row)=>x.action_id)).size).toBe(block.elements.length);expect(view.blocks.filter((x:Row)=>x.type==='section')[0].text.text).toContain('<@U123>');const list=releaseList({batches:Array.from({length:8},(_,i)=>({...b,id:`release-${i}`})),page:1,hasMore:true},source);expect(list.blocks.filter((x:Row)=>x.type==='section')).toHaveLength(8);expect(JSON.stringify(list)).toContain('下一頁');for(const values of Object.values(RELEASE_WORDS))expect(values).toSatisfy((v:string[])=>v.length===3&&v.every(Boolean));expect(JSON.stringify(releaseDetail(b,{...source,locale:'en'},'overview'))).toContain('Records human actions');expect(JSON.stringify(releaseDetail(b,{...source,locale:'zh-CN'},'overview'))).toContain('这里只记录');});
 it('shows the immutable attempt version when recording a result after manifest edits',()=>{const b=batch(),snapshot=structuredClone({title:b.title,ownerId:b.ownerId,components:b.components});b.manifestRevision=2;b.components[0].targets[0].build='v2-current';b.attempts=[{id:'attempt-old',revision:1,environment:'Stage',componentIds:['server'],manifest:snapshot,note:'Old attempt',actorId:'admin',createdAt:'2026-10-01T00:00:00Z',records:[]}];const form=releaseForm('deployed',{batchId:b.id,version:b.version,attemptId:'attempt-old',commandId:'snapshot-command'},source,b,[]);expect(JSON.stringify(form)).toContain('Build／程式版本: v1');expect(JSON.stringify(form)).not.toContain('v2-current');});
 it('pins QA source version in the selected option and never asks users to type raw IDs',()=>{const b=batch(),v=releaseForm('qa',{batchId:b.id,version:1,componentId:'server',commandId:'qa-command'},source,b,['Stage']);expect(v.blocks.filter((b:Row)=>b.type==='input'&&b.block_id.endsWith('Id')).every((b:Row)=>b.element.type==='external_select')).toBe(true);v.state={values:{issueId:{livo_release_qa_issue:{selected_option:{value:JSON.stringify({id:'qa',version:4})}}},targetId:{livo_release_qa_target:{selected_option:{value:'target'}}},runId:{livo_release_qa_run:{selected_option:{value:'run'}}},environment:{value:{selected_option:{value:'Stage'}}},note:{value:{value:'Checked'}}}};expect(releaseSubmission(v,b)).toMatchObject({issueId:'qa',issueVersion:4,targetId:'target',runId:'run'});});
 it('preserves user-selected project tasks and does not interpret mention-like titles',()=>{const v=releaseForm('new',{batchId:'new-batch',version:0,componentId:'component',commandId:'new-command'},source,undefined,['Stage']);v.state={values:Object.fromEntries(Object.entries({name:'<@U123> title',component:'Server',build:'v1',config:'same',data:'none'}).map(([key,value])=>[key,{value:{value}}]))};Object.assign(v.state.values,{owner:{livo_release_owner:{selected_option:{value:'admin'}}},project:{livo_release_project:{selected_option:{value:'p'}}},tasks:{livo_release_tasks:{selected_options:[{value:'task-1'}]}},environment:{value:{selected_option:{value:'Stage'}}}});expect(releaseSubmission(v)).toMatchObject({manifest:{title:'<@U123> title',components:[{taskIds:['task-1']}]}});});
});
describe('release Slack authenticated API adapter',()=>{
 it('uses the member JWT and exact command payload for bounded transport retry',async()=>{const bodies:string[]=[],headers:HeadersInit[]=[];const c={operation:'cancel',commandId:'retry-command',batchId:'release-test',expectedVersion:4,note:'Stop'};const fetcher=vi.fn(async(_url,input)=>{bodies.push(input!.body as string);headers.push(input!.headers!);if(bodies.length===1)throw new Error('network');return Response.json({commandId:c.commandId,batch:batch(),replayed:false,event:{id:'event',batchId:c.batchId,actorId:'admin',operation:'cancel',version:4,revision:1,createdAt:'2026-10-03T00:00:00Z'}});}) as typeof fetch;const d=createReleaseData({get:k=>k==='SUPABASE_URL'?'https://example.com':'anon'},()=>({rows:vi.fn(),request:vi.fn()}),fetcher);await d.request(actor,{action:'command',command:c as never});expect(bodies[0]).toBe(bodies[1]);expect(headers[0]).toMatchObject({Authorization:'Bearer signed-member'});});
 it('does not retry authorization failures or expose raw server messages',async()=>{const fetcher=vi.fn(async()=>Response.json({error:'release_forbidden',detail:'private server data'},{status:403})) as typeof fetch;const d=createReleaseData({get:()=>''},()=>({rows:vi.fn(),request:vi.fn()}),fetcher);await expect(d.request(actor,{action:'get',batchId:'release-test'})).rejects.toMatchObject({code:'release_forbidden'});expect(fetcher).toHaveBeenCalledTimes(1);});
 it('filters QA runs by pinned issue version, target, build and current fix cycle',async()=>{const rows=vi.fn(async()=>[{data:{version:4,fixCycle:2,targets:[{id:'t',component:'Server',environment:'Stage',build:'v1'}],runs:[{id:'old',targetId:'t',build:'v1',fixCycle:1},{id:'current',targetId:'t',build:'v1',fixCycle:2,result:'pass'}]}}]);const d=createReleaseData({get:()=>''},()=>({rows,request:vi.fn()}));const c={projectId:'p',component:'Server',environment:'Stage',build:'v1',issue:{id:'qa',version:4},targetId:'t'};expect((await d.qaOptions(actor,'run','',c)).map(x=>x.value)).toEqual(['current']);expect(await d.qaOptions(actor,'run','',{...c,issue:{id:'qa',version:3}})).toEqual([]);});
});
