import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import type { QaClient } from '@/lib/qa/client';
import type { ReleaseBatch, ReleaseEventPage, ReleaseManifest, ReleaseQaSource } from '@/lib/releases/core';
import ReleaseManifestForm, { type ReleaseResources } from './ReleaseManifestForm';
import ReleaseActionForm, { type ReleaseAction } from './ReleaseActionForm';
import { ReleaseFailure, ReleaseLink, releaseButton, type ReleaseClient } from './ReleaseFields';

export function ReleaseManifestView({ manifest, resources }: { manifest: ReleaseManifest; resources: ReleaseResources }) {
  const { t } = useTranslation();
  return <div className="space-y-3">{manifest.components.map(c => <section key={c.id} className="rounded-lg border p-3"><h3 className="font-medium">{c.name}</h3><p className="text-sm text-muted-foreground">{resources.projects.find(p => p.id === c.projectId)?.name ?? t('releaseWorkspace.unavailable')}</p>{c.taskIds.length > 0 && <ul className="my-2 text-sm">{c.taskIds.map(id => { const task = resources.tasks.find(v => v.id === id && v.projectId === c.projectId); return <li key={id}>{task ? `${task.taskKey} · ${task.title}` : t('releaseWorkspace.unavailableTask')}</li>; })}</ul>}<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['environment', 'build', 'config', 'data'].map(key => <th className="px-2 py-2 font-medium" key={key}>{t(`releaseWorkspace.${key}`)}</th>)}</tr></thead><tbody>{c.targets.map(target => <tr className="border-t" key={target.environment}>{[target.environment, target.build, target.config, target.data].map((value, i) => <td className="break-words px-2 py-2" key={i}>{value}</td>)}</tr>)}</tbody></table></div></section>)}</div>;
}

export default function ReleaseDetail({ batch, resources, client, actorId, canManage, qaClient, qaEnabled, onSource, onSaved, onBack, onRefresh }: {
  batch: ReleaseBatch; resources: ReleaseResources; client: ReleaseClient; actorId: string; canManage: boolean; qaClient: QaClient; qaEnabled: boolean;
  onSource: (source: ReleaseQaSource) => void; onSaved: (batch: ReleaseBatch) => void; onBack: () => void; onRefresh: () => void;
}) {
  const { t } = useTranslation();
  const [action, setAction] = useState<ReleaseAction | 'edit_manifest' | null>(null), [eventPage, setEventPage] = useState(0);
  const [events, setEvents] = useState<ReleaseEventPage | null>(null), [eventError, setEventError] = useState<unknown>(null), [eventRevision, setEventRevision] = useState(0);
  useEffect(() => {
    let active = true; setEvents(null); setEventError(null);
    void client.events(batch.id, eventPage).then(value => { if (active) setEvents(value); }).catch(error => { if (active) setEventError(error); });
    return () => { active = false; };
  }, [client, batch.id, batch.version, eventPage, eventRevision]);
  const name = (id: string) => resources.users.find(u => u.id === id)?.name ?? t('releaseWorkspace.unavailable');
  const saved = (next: ReleaseBatch) => { onSaved(next); setAction(null); setEventPage(0); };
  if (action === 'edit_manifest') return <ReleaseManifestForm batch={batch} actorId={actorId} client={client} resources={resources} onSaved={saved} onCancel={() => setAction(null)} />;
  if (action) return <ReleaseActionForm key={action} batch={batch} action={action} client={client} qaClient={qaClient} qaEnabled={qaEnabled} onSource={onSource} onSaved={saved} onCancel={() => setAction(null)} />;
  const open = batch.status === 'draft' || batch.status === 'active';
  const actions: ReleaseAction[] = open ? ['link_evidence', 'request_exception', 'decide_exception', 'start_attempt', 'record_result', 'record_maintenance', 'complete', 'cancel'] : ['record_result', 'record_maintenance'];
  return <div className="space-y-5">
    <header className="space-y-3"><div className="flex flex-wrap gap-2"><button className={releaseButton} onClick={onBack}>{t('releaseWorkspace.back')}</button><button className={releaseButton} onClick={onRefresh}>{t('releaseWorkspace.refresh')}</button></div><h1 className="text-2xl font-bold break-words">{batch.title}</h1><p className="text-sm text-muted-foreground">{t(`releaseWorkspace.statuses.${batch.status}`)} · {name(batch.ownerId)} · {t('releaseWorkspace.originalRevision', { revision: batch.manifestRevision, version: batch.version })}</p><p className="text-sm text-muted-foreground">{t('releaseWorkspace.intro')}</p>{canManage && <div className="flex flex-wrap gap-2">{open && <button className={releaseButton} onClick={() => setAction('edit_manifest')}>{t('releaseWorkspace.editManifest')}</button>}{actions.map(value => <button className={releaseButton} key={value} onClick={() => setAction(value)}>{t(`releaseWorkspace.operations.${value}`)}</button>)}</div>}{!canManage && <p className="text-xs text-muted-foreground">{t('releaseWorkspace.readOnly')}</p>}</header>
    <section className="space-y-3"><h2 className="text-lg font-semibold">{t('releaseWorkspace.manifest')}</h2><ReleaseManifestView manifest={batch} resources={resources} /></section>
    <section className="space-y-3"><h2 className="text-lg font-semibold">{t('releaseWorkspace.evidence')}</h2>{!batch.evidence.length && <p className="text-sm text-muted-foreground">{t('releaseWorkspace.noEvidence')}</p>}{batch.evidence.map(e => <article key={e.id} className="space-y-2 rounded-lg border p-3"><p className="font-medium">{e.kind.toUpperCase()} · {batch.components.find(c => c.id === e.componentId)?.name ?? t('releaseWorkspace.historicalComponent')} · {e.environment}</p><p className="text-xs text-muted-foreground">{t('releaseWorkspace.revision', { n: e.revision })} · {e.revision !== batch.manifestRevision && t('releaseWorkspace.priorEvidence')} {name(e.actorId)} · {e.createdAt}</p><p className="whitespace-pre-wrap break-words text-sm">{e.note}</p>{e.qa && <><p className="text-sm">{t(`releaseWorkspace.qaResult.${e.qa.result}`)} · {e.qa.build} · {t('releaseWorkspace.qaSnapshot', { version: e.qa.issueVersion, cycle: e.qa.fixCycle })}</p><details className="text-xs"><summary>{t('releaseWorkspace.sourceIds')}</summary><dl><dt>QA</dt><dd>{e.qa.issueId}</dd><dt>{t('releaseWorkspace.qaTarget')}</dt><dd>{e.qa.targetId}</dd><dt>{t('releaseWorkspace.qaRun')}</dt><dd>{e.qa.runId}</dd></dl></details></>}<ReleaseLink url={e.url} /></article>)}</section>
    <section className="space-y-3"><h2 className="text-lg font-semibold">{t('releaseWorkspace.exceptions')}</h2>{!batch.exceptions.length && <p className="text-sm text-muted-foreground">{t('releaseWorkspace.noneRecorded')}</p>}{batch.exceptions.map(e => <article key={e.id} className="space-y-2 rounded-lg border p-3"><p className="font-medium">{e.scope}</p><p className="text-xs text-muted-foreground">{t(`releaseWorkspace.decisions.${e.decision}`)} · {t('releaseWorkspace.revision', { n: e.revision })} · {name(e.requestedBy)} · {e.requestedAt}</p><p className="whitespace-pre-wrap break-words text-sm">{e.reason}</p>{e.decisionNote && <p className="whitespace-pre-wrap break-words text-sm">{e.decidedBy && name(e.decidedBy)} · {e.decidedAt}<br />{e.decisionNote}</p>}</article>)}</section>
    <section className="space-y-3"><h2 className="text-lg font-semibold">{t('releaseWorkspace.attempts')}</h2>{!batch.attempts.length && <p className="text-sm text-muted-foreground">{t('releaseWorkspace.noneRecorded')}</p>}{batch.attempts.map(attempt => <article key={attempt.id} className="space-y-3 rounded-lg border p-3"><p className="font-medium">{attempt.environment} · {t('releaseWorkspace.revision', { n: attempt.revision })}</p><p className="text-xs text-muted-foreground">{name(attempt.actorId)} · {attempt.createdAt}</p><p className="whitespace-pre-wrap break-words text-sm">{attempt.note}</p><p className="text-sm">{t('releaseWorkspace.attemptComponents')}: {attempt.componentIds.map(id => attempt.manifest.components.find(c => c.id === id)?.name ?? t('releaseWorkspace.unavailable')).join(' / ')}</p><details><summary className="cursor-pointer text-sm">{t('releaseWorkspace.originalManifest')}</summary><ReleaseManifestView manifest={attempt.manifest} resources={resources} /></details>{attempt.records.map(record => <div key={record.id} className="space-y-1 border-l-2 pl-3"><p className="text-sm font-medium">{t(`releaseWorkspace.results.${record.type}`)}</p><p className="text-xs text-muted-foreground">{name(record.actorId)} · {record.createdAt}</p><p className="whitespace-pre-wrap break-words text-sm">{record.note}</p><ReleaseLink url={record.url} /></div>)}</article>)}</section>
    <section className="space-y-3"><h2 className="text-lg font-semibold">{t('releaseWorkspace.maintenance')}</h2>{!batch.maintenance.length && <p className="text-sm text-muted-foreground">{t('releaseWorkspace.noneRecorded')}</p>}{batch.maintenance.map(record => <article key={record.id} className="space-y-2 rounded-lg border p-3"><p className="font-medium">{t(record.type === 'start' ? 'releaseWorkspace.maintenanceStart' : 'releaseWorkspace.maintenanceEnd')}</p><p className="text-xs text-muted-foreground">{name(record.actorId)} · {record.createdAt} · {t('releaseWorkspace.revision', { n: record.revision })}</p><p className="whitespace-pre-wrap break-words text-sm">{record.impact}</p><p className="whitespace-pre-wrap break-words text-sm">{record.note}</p></article>)}</section>
    {batch.closureNote && <p className="whitespace-pre-wrap rounded-lg border p-3 text-sm">{batch.closureNote}</p>}
    <section className="space-y-3"><h2 className="text-lg font-semibold">{t('releaseWorkspace.history')}</h2>{eventError !== null ? <><ReleaseFailure error={eventError} /><button className={releaseButton} onClick={() => setEventRevision(v => v + 1)}>{t('releaseWorkspace.refresh')}</button></> : !events ? <p role="status">{t('releaseWorkspace.loading')}</p> : <><ol className="space-y-2 text-sm">{events.events.map(event => <li key={event.id}>{t(event.operation === 'create' ? 'releaseWorkspace.create' : event.operation === 'edit_manifest' ? 'releaseWorkspace.editManifest' : `releaseWorkspace.operations.${event.operation}`)} · {name(event.actorId)} · {event.createdAt} · {t('releaseWorkspace.originalRevision', { version: event.version, revision: event.revision })}</li>)}</ol><div className="flex items-center gap-2"><button className={releaseButton} disabled={eventPage === 0} onClick={() => setEventPage(v => v - 1)}>{t('releaseWorkspace.previous')}</button><span>{t('releaseWorkspace.page', { n: eventPage + 1 })}</span><button className={releaseButton} disabled={!events.hasMore} onClick={() => setEventPage(v => v + 1)}>{t('releaseWorkspace.next')}</button></div></>}</section>
  </div>;
}
