import { SearchableSelect } from '@/components/ui/searchable-select';
import { useEffect,useMemo,useRef,useState } from 'react';
import type { User } from '@/types';
import type { KnowledgePage,KnowledgePolicy } from '@/types/knowledge';
import type { ImportDestination,ImportJob,ImportSource,ImportStoredSource } from '@/types/knowledgeImport';
import { knowledgeCan } from '../../worker/src/knowledgeAccess';
import { knowledgeImportRequest,fileBase64,downloadImportPreview } from '@/lib/knowledgeImportClient';
import { renderKnowledgeHtml } from '@/lib/knowledgeHtml';
import { useKnowledgeImportCapability } from '@/hooks/useKnowledgeImportCapability';
import { useKnowledgeImportText } from '@/hooks/useKnowledgeImportText';
import { useProjectContext } from '@/context/ProjectContext';
import { groupProjectsByLine } from '@/lib/projectGroups';
import { ProjectSelectOptions } from '@/components/project/ProjectOptions';
import { Button } from '@/components/ui/button';
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { KNOWLEDGE_READING_STYLE } from '@/components/knowledge/KnowledgeReadingBody';
import KnowledgePermissionsDialog from '@/components/KnowledgePermissionsDialog';

type TargetPreview={job:ImportJob;destination:ImportDestination;current:{title:string;body:string;version:number}|null;previous:Pick<ImportStoredSource,'body'|'source_key'|'source_hash'|'version'>[];duplicates:Array<{page_id:string;title:string;version:number}>;preserve_manual_body:boolean};
type History=Omit<ImportJob,'items'>&{item_count:number};
const initialDestination=(parent:string|null):ImportDestination=>({parent_id:parent,project_id:null,category:'general',policy:{mode:'inherit'},target_id:null,expected_version:null,mode:'create'});
const control='block mt-1 min-h-11 w-full rounded border border-input bg-background px-3 py-2 text-sm';
export default function KnowledgeImportDialog({open,onOpenChange,pages,users,actor,initialParentId=null,initialTargetId=null,onImported}:{open:boolean;onOpenChange:(value:boolean)=>void;pages:KnowledgePage[];users:User[];actor:User;initialParentId?:string|null;initialTargetId?:string|null;onImported:(ids:string[])=>void}) {
  const text=useKnowledgeImportText(),{allProjects:projects,productLines}=useProjectContext();
  const identity=[actor.id,actor.role,actor.jobTitle,actor.isActive].join('|');const capability=useKnowledgeImportCapability(identity);
  const [step,setStep]=useState(0),[source,setSource]=useState<ImportSource>('docx'),[file,setFile]=useState<File|null>(null),[notion,setNotion]=useState(''),[job,setJob]=useState<ImportJob|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState<History[]>([]),[reviewed,setReviewed]=useState(false),[partial,setPartial]=useState(false),[audience,setAudience]=useState(false),[destination,setDestination]=useState(initialDestination(initialParentId)),[preview,setPreview]=useState<TargetPreview|null>(null),[permissionsOpen,setPermissionsOpen]=useState(false);
  const generation=useRef(0),pollError=useRef('');const activeActor={...actor,is_active:actor.isActive};
  // Pages go three levels deep: a page that already has a grandparent cannot take children.
  const tooDeep=(page:{parent_id:string|null})=>{const parent=page.parent_id?pages.find(p=>p.id===page.parent_id):undefined;return !!parent?.parent_id;};
  const visible=useMemo(()=>pages.filter(p=>knowledgeCan(pages,p.id,{...actor,is_active:actor.isActive},'view')),[pages,identity]);
  const canEdit=(id:string)=>knowledgeCan(pages,id,activeActor,'edit');
  const run=async<T,>(action:string,values:Record<string,unknown>,success:(data:T)=>void)=>{const current=generation.current;setBusy(true);setError('');try{const data=await knowledgeImportRequest<T>(action,values);if(current===generation.current)success(data);}catch(e){if(current===generation.current){const message=e instanceof Error?e.message:'import_failed';setError(message);if(/forbidden|expired/.test(message)){setJob(null);setPreview(null);setStep(0);}}}finally{if(current===generation.current)setBusy(false);}};
  useEffect(()=>{generation.current++;setJob(null);setPreview(null);setStep(0);setHistory([]);setReviewed(false);setPartial(false);setAudience(false);setError('');},[identity]);
  useEffect(()=>{if(!open)return;const target=pages.find(p=>p.id===initialTargetId);setDestination(d=>({...d,parent_id:target?.parent_id||initialParentId,project_id:target?.project_id||pages.find(p=>p.id===initialParentId)?.project_id||null,mode:target?'update':'create',target_id:target?.id||null,expected_version:target?.version||null}));if(capability.allowed)void run<History[]>('list',{},setHistory);},[open,initialParentId,initialTargetId,capability.allowed]);
  useEffect(()=>{if(!open||!job)return;let active=true,request=0;const id=job.id;const refresh=():void=>{const ticket=++request;void knowledgeImportRequest<ImportJob>('get',{job_id:id}).then(value=>{if(active&&ticket===request){setJob(value);if(pollError.current){const shown=pollError.current;pollError.current='';setError(current=>current===shown?'':current);}}}).catch(e=>{if(active&&ticket===request){const message=e instanceof Error?e.message:'import_failed';
    // Keep the job through a failed refresh (the Edge worker can stop while the private
    // parse goes on); drop it only when the job itself is gone or out of reach.
    if(/forbidden|expired|job_not_found/.test(message)){setJob(null);setPreview(null);setStep(0);}pollError.current=message;setError(message);}});};const timer=setInterval(refresh,['uploaded','parsing','committing'].includes(job.status)?2000:30000);window.addEventListener('focus',refresh);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',refresh);};},[open,job?.id,job?.status]);
  useEffect(()=>{if(destination.target_id&&!visible.some(p=>p.id===destination.target_id)){setPreview(null);setDestination(d=>({...d,target_id:null,expected_version:null}));setError('import_forbidden');}},[visible,destination.target_id]);
  useEffect(()=>{if(!capability.loading&&!capability.allowed){setJob(null);setPreview(null);setHistory([]);setStep(0);}},[capability.allowed,capability.loading]);
  const changeDestination=(next:Partial<ImportDestination>)=>{setDestination(previous=>({...previous,...next}));setPreview(null);setAudience(false);};
  const start=async()=>{setReviewed(false);setPartial(false);setPreview(null);setAudience(false);try{const data=source==='notion'?{source,page_ids:notion.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}:{source,name:file?.name,data:file?await fileBase64(file):''};await run<ImportJob>('start',{...data,parent_id:initialTargetId||initialParentId},value=>{setJob(value);setStep(1);});}catch(e){setError(e instanceof Error?e.message:'invalid_file');}};
  const checkTarget=()=>job&&run<TargetPreview>('preview_target',{job_id:job.id,destination},value=>{setJob(value.job);setPreview(value);});
  // The destination is checked as soon as it is complete; the button stays for a retry after an error.
  const jobId=job?.id;
  useEffect(()=>{if(step!==2||!jobId||preview||busy||(destination.mode==='update'&&!destination.target_id))return;const timer=setTimeout(()=>{void checkTarget();},300);return()=>clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  },[step,jobId,destination,preview]);
  const commit=()=>job&&run<ImportJob>('commit',{job_id:job.id,version:job.version,mappings:job.items.filter(i=>i.status==='ready'||i.status==='committed').map(item=>({item_id:item.id,destination,reviewed,allow_incomplete:partial,confirm_audience:audience}))},value=>{setJob(value);setStep(3);onImported(value.items.flatMap(i=>i.page_id?[i.page_id]:[]));});
  const retryParsing=()=>job&&run<ImportJob>('retry',{job_id:job.id},value=>{setJob(value);setPreview(null);setReviewed(false);setPartial(false);setAudience(false);setStep(1);});
  const parseRetryAvailable=job?.items.some(item=>item.status!=='committed'&&(item.status==='failed'||item.parsed?.incomplete));
  const commitRetryAvailable=job?.items.some(item=>item.status==='ready'&&!!item.parsed);
  const pending=!!job&&['uploaded','parsing','committing'].includes(job.status),incomplete=job?.items.some(i=>i.status!=='committed'&&i.parsed?.incomplete),ready=job?.items.some(i=>i.status==='ready');
  const disabled=busy||pending;
  // Markdown and Notion are converted by LIVO itself; Word and PDF need the private processor.
  useEffect(()=>{if(!capability.loading&&!capability.processor_configured&&step===0&&!file&&source==='docx')setSource('md');
    // eslint-disable-next-line react-hooks/exhaustive-deps
  },[capability.loading,capability.processor_configured]);
  const processorMissing=!capability.processor_configured&&(source==='docx'||source==='pdf');
  return <><Dialog open={open} onOpenChange={value=>{if(!busy)onOpenChange(value);}}><DialogContent className="max-w-4xl max-h-[92vh] overflow-auto"><DialogHeader><DialogTitle>{text('title')}</DialogTitle><DialogDescription>{text('sourceHelp')}</DialogDescription></DialogHeader>
    <ol className="flex flex-wrap gap-3 text-sm" aria-label={text('title')}>{['source','preview','destination','result'].map((s,index)=><li key={s} aria-current={step===index?'step':undefined} className={step===index?'font-semibold text-primary':'text-muted-foreground'}>{index+1}. {text(s)}</li>)}</ol>
    {error&&<p role="alert" className="rounded bg-destructive/10 p-3 text-sm text-destructive">{text(error)}</p>}
    {capability.loading?<p role="status">{text('busy')}</p>:!capability.allowed?<p role="alert">{text('import_forbidden')}</p>:<>
      {step===0&&processorMissing&&<p role="alert" className="rounded bg-amber-500/10 p-3 text-sm">{text('processorMissing')}</p>}
      {step===0&&<div className="space-y-4"><div className="grid grid-cols-2 sm:grid-cols-4 gap-2">{(['notion','docx','md','pdf'] as const).map(type=><Button key={type} variant={source===type?'default':'outline'} className="min-h-11" aria-pressed={source===type} disabled={busy||(type==='notion'&&!capability.notion_available)} onClick={()=>{setSource(type);setFile(null);}}>{type==='notion'?'Notion':type==='docx'?'Word .docx':type==='md'?'Markdown .md':'PDF .pdf'}</Button>)}</div>
        {source==='notion'?<label className="block text-sm">{text('notionHelp')}<textarea className={control} rows={4} value={notion} onChange={e=>setNotion(e.target.value)}/></label>:<label className="block text-sm">{text('chooseFile')}<input key={source} type="file" accept={`.${source}`} className={control} onChange={e=>{setFile(e.target.files?.[0]||null);setError('');}}/></label>}
        {!capability.notion_available&&<p className="text-xs text-muted-foreground">{text('notionUnavailable')}</p>}
        <Button className="min-h-11" disabled={busy||processorMissing||(source==='notion'?!notion.trim():!file)} onClick={()=>void start()}>{text(busy?'busy':'start')}</Button>
        <details><summary className="cursor-pointer min-h-11 py-3">{text('history')}</summary>{!history.length?<p className="text-sm text-muted-foreground">{text('noHistory')}</p>:<ul className="space-y-2">{history.map(item=><li key={item.id} className="flex items-center justify-between gap-3 border rounded p-2 text-sm"><span>{new Date(item.created_at).toLocaleString()} · {item.source} · {text(item.status)}</span><Button variant="outline" className="min-h-11" onClick={()=>void run<ImportJob>('get',{job_id:item.id},value=>{setJob(value);setSource(value.source);setStep(value.status==='succeeded'?3:1);})}>{text('resume')}</Button></li>)}</ul>}</details>
      </div>}
      {step===1&&job&&<div className="space-y-4"><p role="status" className="text-sm font-medium">{text(job.status)}</p><p className="rounded bg-amber-500/10 p-3 text-sm">{text('historyWarning')}</p>{incomplete&&<p role="alert" className="rounded bg-amber-500/10 p-3 text-sm">{text('incomplete')}</p>}
        {job.items.map(item=><section key={item.id} className="rounded border p-4 space-y-3"><h3 className="font-semibold">{item.title} <span className="text-xs font-normal text-muted-foreground">{text(item.status)}</span></h3>{item.error&&<p role="alert" className="text-sm text-destructive">{text(item.error)}</p>}
          {item.original.size>0&&<Button variant="outline" className="min-h-11" onClick={()=>void downloadImportPreview(job.id,item.id).catch(e=>{const message=e instanceof Error?e.message:'import_failed';setError(message);
            // Only losing access ends the import; a failed download leaves the reviewed preview where it is.
            if(/forbidden/.test(message)){setJob(null);setPreview(null);setStep(0);}})}>{text('download')}</Button>}
          {item.parsed&&<><ul className="text-sm text-amber-800 dark:text-amber-300">{item.parsed.warnings.map((warning,index)=><li key={index}>{text(warning)}</li>)}</ul>{!!item.parsed.pages.length&&<ul className="flex flex-wrap gap-2 text-xs">{item.parsed.pages.map(page=><li key={page.page} className="rounded border px-2 py-1">{text('page')} {page.page} · {text(page.state)}{page.confidence!==null?` · ${page.confidence}%`:''}</li>)}</ul>}<div className={KNOWLEDGE_READING_STYLE+' max-h-96 overflow-auto rounded border p-3'} dangerouslySetInnerHTML={{__html:renderKnowledgeHtml(item.parsed.body)}}/></>}
        </section>)}
        {!pending&&<><label className="flex min-h-11 gap-2 items-start py-3 text-sm"><input className="mt-1" type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>{text('reviewed')}</label>{incomplete&&<label className="flex min-h-11 gap-2 items-start py-3 text-sm"><input className="mt-1" type="checkbox" checked={partial} onChange={e=>setPartial(e.target.checked)}/>{text('acceptPartial')}</label>}</>}
        <div className="flex flex-wrap gap-2"><Button variant="outline" className="min-h-11" disabled={disabled} onClick={()=>setStep(0)}>{text('back')}</Button><Button className="min-h-11" disabled={disabled||!ready||!reviewed||(!!incomplete&&!partial)} onClick={()=>setStep(2)}>{text('next')}</Button>{!pending&&parseRetryAvailable&&job.status!=='cancelled'&&<Button variant="outline" className="min-h-11" disabled={busy} onClick={()=>void retryParsing()}>{text('retry')}</Button>}{job.status!=='committing'&&<Button variant="ghost" className="min-h-11" disabled={busy} onClick={()=>void run<ImportJob>('cancel',{job_id:job.id},setJob)}>{text('cancel')}</Button>}</div>
      </div>}
      {step===2&&job&&<div className="space-y-4"><p className="text-sm text-muted-foreground">{text('hierarchy')}</p>
        <label className="block text-sm">{text('mode')}<SearchableSelect className={control} value={destination.mode} onChange={e=>changeDestination({mode:e.target.value as ImportDestination['mode'],target_id:null,expected_version:null})}><option value="create">{text('create')}</option><option value="update">{text('update')}</option><option value="copy">{text('copy')}</option></SearchableSelect></label>
        {destination.mode==='update'?<label className="block text-sm">{text('target')}<SearchableSelect className={control} value={destination.target_id||''} onChange={e=>{const page=visible.find(p=>p.id===e.target.value);changeDestination({target_id:page?.id||null,expected_version:page?.version||null,parent_id:page?.parent_id||null,project_id:page?.project_id||null,policy:page?.access_policy||{mode:'inherit'}});}}><option value="">—</option>{visible.map(page=>{const deep=tooDeep(page);return <option key={page.id} value={page.id} disabled={!canEdit(page.id)||deep}>{page.title}{!canEdit(page.id)?` · ${text('readOnly')}`:deep?` · ${text('depthFull')}`:''}</option>;})}</SearchableSelect></label>:<>
          <label className="block text-sm">{text('parent')}<SearchableSelect className={control} value={destination.parent_id||''} onChange={e=>{const parent=visible.find(p=>p.id===e.target.value);changeDestination({parent_id:parent?.id||null,project_id:parent?.project_id||null});}}><option value="">{text('root')}</option>{visible.map(page=>{const deep=tooDeep(page);return <option key={page.id} value={page.id} disabled={!canEdit(page.id)||deep}>{page.title}{!canEdit(page.id)?` · ${text('readOnly')}`:deep?` · ${text('depthFull')}`:''}</option>;})}</SearchableSelect></label>
          <div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm">{text('scope')}<SearchableSelect className={control} disabled={!!destination.parent_id} value={destination.project_id||''} onChange={e=>changeDestination({project_id:e.target.value||null})}><option value="">{text('shared')}</option><ProjectSelectOptions groups={groupProjectsByLine(productLines,projects)}/></SearchableSelect></label><label className="block text-sm">{text('category')}<SearchableSelect className={control} value={destination.category} onChange={e=>changeDestination({category:e.target.value as 'general'|'meeting'})}><option value="general">{text('general')}</option><option value="meeting">{text('meeting')}</option></SearchableSelect></label></div>
          <div className="flex items-center justify-between gap-3"><p className="text-sm">{text('access')} · {text(destination.policy.mode==='custom'?'custom':'inherit')}</p>{['admin','super_admin'].includes(actor.role)&&<Button variant="outline" className="min-h-11" onClick={()=>setPermissionsOpen(true)}>{text('access')}</Button>}</div>
        </>}
        {destination.mode==='update'&&<p className="rounded bg-blue-500/10 p-3 text-sm">{text('preserve')}</p>}
        <Button variant="outline" className="min-h-11" disabled={busy||(destination.mode==='update'&&!destination.target_id)} onClick={()=>void checkTarget()}>{text('checkDestination')}</Button>
        {!!preview?.duplicates?.length&&<div role="alert" className="rounded bg-amber-500/10 p-3 space-y-2 text-sm"><p>{text('duplicate_source')}</p>{preview.duplicates.map(match=><Button key={match.page_id} variant="outline" className="min-h-11 max-w-full" disabled={!canEdit(match.page_id)} onClick={()=>{const p=visible.find(x=>x.id===match.page_id);changeDestination({mode:'update',target_id:match.page_id,expected_version:match.version,parent_id:p?.parent_id||null,project_id:p?.project_id||null});}}>{text('update')} · {match.title}</Button>)}</div>}
        {preview&&<><div className="grid gap-3 sm:grid-cols-3">{[{label:'previous',body:preview.previous[0]?.body},{label:'current',body:preview.current?.body},{label:'incoming',body:job.items.find(item=>item.status==='ready')?.parsed?.body}].map(column=><details key={column.label} className="rounded border p-3"><summary className="min-h-11 cursor-pointer py-2 text-sm font-medium">{text(column.label)}</summary><div className={KNOWLEDGE_READING_STYLE+' max-h-64 overflow-auto'} dangerouslySetInnerHTML={{__html:renderKnowledgeHtml(column.body||'')}}/></details>)}</div><label className="flex gap-2 min-h-11 py-3 items-start text-sm"><input type="checkbox" className="mt-1" checked={audience} onChange={e=>setAudience(e.target.checked)}/>{text('audience')}</label></>}
        <div className="flex gap-2"><Button variant="outline" className="min-h-11" disabled={busy} onClick={()=>setStep(1)}>{text('back')}</Button><Button className="min-h-11" disabled={busy||!preview||!audience||!!preview?.duplicates?.length} onClick={()=>void commit()}>{text(busy?'busy':'commit')}</Button></div>
      </div>}
      {step===3&&job&&<div className="space-y-4"><p role="status" className="font-medium">{text(job.status)}</p><p className="text-sm text-muted-foreground">{text('successHelp')}</p><ul className="space-y-2">{job.items.map(item=><li key={item.id} className="border rounded p-3 text-sm"><strong>{item.title}</strong> · {text(item.status)}{item.error&&<p role="alert">{text(item.error)}</p>}{item.parsed?.incomplete&&<p className="text-amber-700">{text('incomplete')}</p>}</li>)}</ul><div className="flex gap-2">{job.status==='partially_failed'&&<>{parseRetryAvailable&&<Button variant="outline" className="min-h-11" disabled={busy} onClick={()=>void retryParsing()}>{text('retry')}</Button>}{commitRetryAvailable&&<Button variant="outline" className="min-h-11" disabled={busy} onClick={()=>{setPreview(null);setAudience(false);setStep(2);}}>{text('retryCommit')}</Button>}</>}<Button className="min-h-11" onClick={()=>onOpenChange(false)}>{text('close')}</Button></div></div>}
    </>}
  </DialogContent></Dialog><KnowledgePermissionsDialog open={permissionsOpen} onOpenChange={setPermissionsOpen} policy={destination.policy} users={users} currentMemberId={actor.id} hasParent={!!destination.parent_id} busy={false} onSave={async(policy:KnowledgePolicy)=>{changeDestination({policy});setPermissionsOpen(false);}}/></>;
}
