-- ISOLATED TEST DATABASE ONLY. Extends qa-postgres-fixture.sql, never production.
CREATE SCHEMA extensions;
CREATE EXTENSION pgcrypto WITH SCHEMA extensions;
ALTER TABLE public.members ADD COLUMN job_title text NOT NULL DEFAULT '';
ALTER TABLE public.members ADD COLUMN email text;
ALTER TABLE public.members ADD COLUMN name text NOT NULL DEFAULT 'Example member';
ALTER TABLE public.projects ADD COLUMN name text NOT NULL DEFAULT 'Example project';
ALTER TABLE public.projects ADD COLUMN key text NOT NULL DEFAULT 'EX';
CREATE TABLE public.statuses(id text PRIMARY KEY,name text NOT NULL,is_done boolean NOT NULL DEFAULT false,sort_order integer NOT NULL DEFAULT 0);
INSERT INTO public.statuses(id,name) VALUES('s-open','Open');
INSERT INTO public.statuses(id,name,is_done) VALUES('s-done','Done',true);
ALTER TABLE public.tasks ADD COLUMN task_key text NOT NULL DEFAULT 'EX-1';
ALTER TABLE public.tasks ADD COLUMN title text NOT NULL DEFAULT 'Example task';
ALTER TABLE public.tasks ADD COLUMN status_id text REFERENCES public.statuses(id) DEFAULT 's-open';
ALTER TABLE public.tasks ADD COLUMN priority text NOT NULL DEFAULT 'medium';
ALTER TABLE public.tasks ADD COLUMN creator_id text;
ALTER TABLE public.tasks ADD COLUMN assignee_id text;
ALTER TABLE public.tasks ADD COLUMN due_date text;
CREATE TABLE public.task_specs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),task_id text UNIQUE REFERENCES public.tasks(id),background text,requirement text,notes text);
CREATE TABLE public.task_todos(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),task_id text REFERENCES public.tasks(id),text text,is_done boolean NOT NULL DEFAULT false,sort_order integer DEFAULT 0);
CREATE TABLE public.task_deployments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),task_id text REFERENCES public.tasks(id),environment text,status text,deploy_date text);
CREATE TABLE public.activity_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id text,action text,target_type text,task_id text,task_key text,detail text,created_at timestamptz DEFAULT now());
CREATE TABLE public.field_locks(lock_key text PRIMARY KEY,locked_by text,expires_at timestamptz);
CREATE TABLE public.external_account_bindings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),member_id text,platform text,platform_user_id text,platform_team_id text,is_verified boolean DEFAULT false,verified_by text);
CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql STABLE AS $$ SELECT COALESCE(nullif(current_setting('request.jwt.claims',true),'')::jsonb,'{}')||jsonb_build_object('sub',auth.uid(),'role',COALESCE(nullif(current_setting('request.jwt.claim.role',true),''),'authenticated')) $$;
CREATE FUNCTION auth.email() RETURNS text LANGUAGE sql STABLE AS $$ SELECT auth.jwt()->>'email' $$;
CREATE FUNCTION public.current_member_id() RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT id FROM public.members WHERE auth_id=auth.uid() AND is_active LIMIT 1 $$;
CREATE FUNCTION public.current_member_role() RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT role FROM public.members WHERE auth_id=auth.uid() AND is_active LIMIT 1 $$;
CREATE FUNCTION public.is_livo_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT COALESCE(public.current_member_role() IN('admin','super_admin'),false) $$;
CREATE FUNCTION public.livo_slack_session() RETURNS boolean LANGUAGE sql STABLE SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.external_account_bindings b JOIN public.members m ON m.id=b.member_id WHERE b.id::text=auth.jwt()->>'livo_slack_binding' AND b.platform='slack' AND b.is_verified AND m.id=public.current_member_id() AND m.is_active AND m.auth_id=auth.uid()) $$;
CREATE PUBLICATION supabase_realtime;
GRANT SELECT ON public.members,public.projects,public.statuses,public.tasks,public.external_account_bindings,storage.buckets TO authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.field_locks TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
UPDATE public.members SET job_title='PM' WHERE id='m-member';
INSERT INTO public.members(id,auth_id,role,is_active,job_title) VALUES('m-kb-seed','00000000-0000-0000-0000-000000000006','admin',true,'PM');
CREATE OR REPLACE FUNCTION public.livo_slack_enabled() RETURNS boolean LANGUAGE sql STABLE SET search_path=public AS $$ SELECT COALESCE((SELECT value->'slackActions'='true'::jsonb FROM public.system_settings WHERE key='feature_toggles'),false) $$;
CREATE FUNCTION public.livo_guard_slack_binding() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$ BEGIN
 IF current_user IN ('anon','authenticated') AND ((TG_OP<>'DELETE' AND NEW.platform='slack') OR (TG_OP<>'INSERT' AND OLD.platform='slack')) THEN RAISE EXCEPTION 'Slack bindings are managed by the server' USING ERRCODE='42501'; END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF; END $$;
CREATE TRIGGER livo_guard_slack_binding BEFORE INSERT OR UPDATE OR DELETE ON public.external_account_bindings FOR EACH ROW EXECUTE FUNCTION public.livo_guard_slack_binding();
GRANT INSERT,UPDATE,DELETE ON public.external_account_bindings TO authenticated;
