// @vitest-environment node
// Real SQLite schema, transaction boundaries and Worker adapter; synthetic data only.
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import path from 'node:path';
import {tmpdir} from 'node:os';
import {Worker} from 'node:worker_threads';
import {applyPostTenantSchemaUpgrades} from '../../worker/migrate/schema-upgrades.mjs';
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
vi.mock('../../worker/src/notify',()=>({notifyChanges:()=>{}}));
import {executeKnowledgeWork,knowledgeSnapshot} from '../../worker/src/knowledgeWork';
import {queryKnowledgeState} from '../../src/lib/knowledgeWork/engine';
import {parseKnowledgeWorkCommand} from '../../src/lib/knowledgeWork/core';
import {knowledgePermissionSql} from '../../worker/src/knowledgeSql';
let db,env,sequence,beforeBatch,temp,file;
const auth=(id='member',ws='a')=>({userId:id,member:{id,workspaceId:ws,role:'member',email:`${id}@example.com`},email:`${id}@example.com`});
const command=(operation,fields={})=>({commandId:`knowledge-command-${++sequence}`,operation,...fields});
const sql=()=>db.prepare('SELECT * FROM kb_pages ORDER BY id').all();
const query=async(q,a=auth())=>queryKnowledgeState(await knowledgeSnapshot(env,a,q.operation==='command_result'?q.commandId:null),q);
const preview=()=>query({operation:'prepare_draft',input:{kind:'meeting',title:'Synthetic meeting',notes:'Proposal, not an approved decision.',sourceRefs:[]}});
const save=async(a=auth())=>executeKnowledgeWork(env,a,command('save_draft',{preview:await preview(),title:'Synthetic meeting',text:'Draft content',confirmed:true}));
beforeEach(()=>{
 sequence=0;beforeBatch=null;temp=fs.mkdtempSync(path.join(tmpdir(),'livo-knowledge-native-'));file=path.join(temp,'db.sqlite');db=new DatabaseSync(file);db.exec('PRAGMA foreign_keys=ON;PRAGMA journal_mode=WAL;PRAGMA busy_timeout=3000;');
 db.exec(fs.readFileSync(new URL('../../worker/schema.sql',import.meta.url),'utf8'));
 db.exec(fs.readFileSync(new URL('../../worker/migrate/knowledge-work.sql',import.meta.url),'utf8'));
 db.exec(fs.readFileSync(new URL('../../worker/migrate/knowledge-work.sql',import.meta.url),'utf8'));
 db.exec(`INSERT INTO workspaces(id,name) VALUES('a','Synthetic A'),('b','Synthetic B');
 INSERT INTO product_lines(workspace_id,id,name) VALUES('a','la','A'),('b','lb','B');
 INSERT INTO projects(workspace_id,id,line_id,name,key,is_archived) VALUES('a','p','la','P','P',0),('b','q','lb','Q','Q',0);
 INSERT INTO statuses(workspace_id,id,name) VALUES('a','todo','Todo');`);
 for(const id of ['member','other','admin','foreign']){
  const ws=id==='foreign'?'b':'a';db.prepare('INSERT INTO auth_users(id,email) VALUES(?,?)').run(id,`${id}@example.com`);
  db.prepare('INSERT INTO members(workspace_id,id,name,avatar,email,role,auth_id) VALUES(?,?,?,?,?,?,?)').run(ws,id,id,'',`${id}@example.com`,id==='admin'?'admin':'member',id);
 }
 db.prepare('INSERT INTO kb_pages(workspace_id,id,title,body,created_by,updated_by,project_id) VALUES(?,?,?,?,?,?,?)').run('a','guide','Synthetic guide','<p>First specification</p>','member','member','p');
 db.prepare('INSERT INTO kb_pages(workspace_id,id,title,body,created_by,updated_by,project_id) VALUES(?,?,?,?,?,?,?)').run('b','foreign-guide','Private other workspace','Other content','foreign','foreign','q');
 const make=(sqlText,params=[])=>({sqlText,params,bind(...values){return make(sqlText,values);},async all(){return {results:db.prepare(sqlText).all(...params)};},async first(){return db.prepare(sqlText).get(...params)||null;},async run(){const r=db.prepare(sqlText).run(...params);return {success:true,meta:{changes:Number(r.changes)},results:[]};}});
 env={DB:{prepare:make,async batch(statements){if(beforeBatch&&statements[0].sqlText.startsWith('INSERT INTO kb_work_contexts')){const fn=beforeBatch;beforeBatch=null;await fn();}
  db.exec('BEGIN');try{const result=statements.map(s=>({success:true,results:db.prepare(s.sqlText).all(...s.params)}));db.exec('COMMIT');return result;}catch(error){db.exec('ROLLBACK');throw error;}}}};
});
afterEach(()=>{db.close();if(!temp.startsWith(path.resolve(tmpdir())+path.sep+'livo-knowledge-native-'))throw new Error('Unsafe cleanup');fs.rmSync(temp,{recursive:true,force:true});});
describe('Knowledge domain on native SQLite',()=>{
 it('preview performs no writes and reports selected-source coverage',async()=>{const before=JSON.stringify(sql());const p=await preview();expect(p.coverage.limitations).toContain('selected_sources_only');expect(JSON.stringify(sql())).toBe(before);expect(db.prepare('SELECT count(*) n FROM kb_work_receipts').get().n).toBe(0);});
 it('saves exactly once and replays a fresh private detail',async()=>{const c=command('save_draft',{preview:await preview(),title:'Draft',text:'Text',confirmed:true});const a=await executeKnowledgeWork(env,auth(),c),b=await executeKnowledgeWork(env,auth(),c);expect(b.replayed).toBe(true);expect(b.page.pageId).toBe(a.page.pageId);expect(db.prepare('SELECT count(*) n FROM kb_work_receipts').get().n).toBe(1);expect(db.prepare('SELECT count(*) n FROM kb_work_contexts').get().n).toBe(0);});
 it('receipt result lookup requires its owner and fresh visibility',async()=>{const saved=await save();const q={operation:'command_result',commandId:saved.commandId};expect((await query(q)).result.page.pageId).toBe(saved.page.pageId);expect(await query(q,auth('admin'))).toEqual({found:false});db.prepare('UPDATE members SET is_active=0 WHERE id=?').run('member');await expect(query(q)).rejects.toThrow('knowledge_forbidden');});
 it('does not allow an admin to read another member private draft through query or generic SQL predicate',async()=>{const saved=await save();await expect(query({operation:'detail',pageId:saved.page.pageId},auth('admin'))).rejects.toThrow('knowledge_unavailable');const pred=knowledgePermissionSql('kb_pages.id','view',auth('admin'));expect(db.prepare(`SELECT id FROM kb_pages WHERE workspace_id=? AND id=? AND ${pred.sql}`).all('a',saved.page.pageId,...pred.params)).toHaveLength(0);});
 it('refuses ordinary writes that clear the private owner or change its hierarchy',async()=>{const saved=await save();expect(()=>db.prepare('UPDATE kb_pages SET private_draft_owner_id=NULL WHERE id=?').run(saved.page.pageId)).toThrow('knowledge_forbidden');expect(()=>db.prepare('UPDATE kb_pages SET project_id=? WHERE id=?').run('p',saved.page.pageId)).toThrow('knowledge_forbidden');});
 it('allows explicit ordinary-member sharing into an editable destination',async()=>{const saved=await save();const shared=await executeKnowledgeWork(env,auth(),command('share_draft',{pageId:saved.page.pageId,expectedVersion:1,projectId:'p',parentId:'guide',confirmed:true}));expect(shared.page.privateDraftOwnerId).toBeNull();expect((await query({operation:'detail',pageId:saved.page.pageId},auth('other'))).title).toBe('Synthetic meeting');});
 it('keeps a private draft private when its source ACL would be widened',async()=>{const policy={mode:'custom',view:{roles:[],positions:[],member_ids:['member']},edit:{roles:[],positions:[],member_ids:['member']},comment:{roles:[],positions:[],member_ids:['member']}};db.prepare('UPDATE kb_pages SET access_policy=? WHERE id=?').run(JSON.stringify(policy),'guide');const refs=(await query({operation:'search',query:'guide',types:['knowledge'],projectIds:[],effectiveOnly:false,cursor:0})).items.map(({kind,id,version})=>({kind,id,version}));const p=await query({operation:'prepare_draft',input:{kind:'meeting',notes:'',sourceRefs:refs}});const saved=await executeKnowledgeWork(env,auth(),command('save_draft',{preview:p,title:'Draft',text:p.text,confirmed:true}));await expect(executeKnowledgeWork(env,auth(),command('share_draft',{pageId:saved.page.pageId,expectedVersion:1,projectId:null,parentId:null,confirmed:true}))).rejects.toThrow('knowledge_scope_conflict');expect(db.prepare('SELECT private_draft_owner_id FROM kb_pages WHERE id=?').get(saved.page.pageId).private_draft_owner_id).toBe('member');});
 it('publishes a pinned revision and protects it from 20-version pruning',async()=>{let r=await executeKnowledgeWork(env,auth(),command('set_metadata',{pageId:'guide',expectedVersion:1,metadata:{documentKind:'specification',ownerId:'member',applicability:{productVersion:'1.0',environment:null,summary:null}}}));r=await executeKnowledgeWork(env,auth(),command('publish',{pageId:'guide',expectedVersion:r.page.pageVersion,expectedPublicationId:null,confirmed:true}));const v=r.page.publication.page_version;for(let i=0;i<25;i++)db.prepare('UPDATE kb_pages SET body=?,version=version+1 WHERE id=?').run('Changed '+i,'guide');const detail=await query({operation:'detail',pageId:'guide'});expect(detail.publication.body).toBe('<p>First specification</p>');expect(db.prepare('SELECT count(*) n FROM kb_revisions WHERE page_id=? AND version=?').get('guide',v).n).toBe(1);});
 it('generation CAS rolls back when permissions change between plan and transaction',async()=>{beforeBatch=()=>db.prepare('UPDATE members SET is_active=0 WHERE id=?').run('member');await expect(executeKnowledgeWork(env,auth(),command('save_draft',{preview:await preview(),title:'Draft',text:'x',confirmed:true}))).rejects.toThrow('knowledge_forbidden');expect(db.prepare('SELECT count(*) n FROM kb_work_receipts').get().n).toBe(0);});
 it('generation CAS rolls back after an unrelated source write instead of silently using stale data',async()=>{beforeBatch=()=>db.prepare('UPDATE kb_pages SET title=? WHERE id=?').run('Concurrent title','guide');await expect(save()).rejects.toThrow('knowledge_conflict');expect(db.prepare('SELECT count(*) n FROM kb_work_events').get().n).toBe(0);});
 it('rechecks membership on replay and never returns the cached body',async()=>{const c=command('save_draft',{preview:await preview(),title:'Draft',text:'sensitive synthetic',confirmed:true});await executeKnowledgeWork(env,auth(),c);db.prepare('UPDATE members SET is_active=0 WHERE id=?').run('member');await expect(executeKnowledgeWork(env,auth(),c)).rejects.toThrow('knowledge_forbidden');});
 it('does not cross workspace boundaries or expose private search filenames',async()=>{const results=await query({operation:'search',query:'',types:['knowledge'],projectIds:[],effectiveOnly:false,cursor:0});expect(results.items.map(x=>x.id)).toEqual(['guide']);});
 it.each([['member',"UPDATE members SET is_active=0 WHERE id='member'"],['source',"UPDATE kb_pages SET title='Other writer' WHERE id='guide'"]])('independent SQLite writer %s commits before waiting command can write',async(_label,sql)=>{
  let done;beforeBatch=()=>new Promise((ready,reject)=>{const w=new Worker(`const {workerData,parentPort}=require('node:worker_threads');const {DatabaseSync}=require('node:sqlite');const db=new DatabaseSync(workerData.file);db.exec('PRAGMA busy_timeout=3000; BEGIN IMMEDIATE;'+workerData.sql);parentPort.postMessage('ready');setTimeout(()=>{db.exec('COMMIT');db.close();parentPort.postMessage('done');},250);`,{eval:true,workerData:{file,sql}});done=new Promise((resolve,fail)=>{w.on('message',m=>m==='ready'?ready():resolve());w.on('error',e=>{reject(e);fail(e);});});});
  await expect(save()).rejects.toThrow(/knowledge_(forbidden|conflict)/);await done;expect(db.prepare('SELECT count(*) n FROM kb_work_receipts').get().n).toBe(0);expect(db.prepare('SELECT count(*) n FROM kb_work_contexts').get().n).toBe(0);
 });
 it('new migration probes apply twice without duplicate columns or lost receipts',async()=>{const saved=await save();const deps={queryRows:async sql=>db.prepare(sql).all(),applyFile:async name=>db.exec(fs.readFileSync(new URL('../../worker/migrate/'+name,import.meta.url),'utf8'))};await applyPostTenantSchemaUpgrades(deps);await applyPostTenantSchemaUpgrades(deps);expect((await query({operation:'detail',pageId:saved.page.pageId})).privateDraftOwnerId).toBe('member');expect(db.prepare('SELECT count(*) n FROM kb_work_receipts').get().n).toBe(1);});
 it('upgrades the previous KB column shape twice and preserves existing page bodies',async()=>{
  const old=new DatabaseSync(':memory:');try{let schema=fs.readFileSync(new URL('../../worker/schema.sql',import.meta.url),'utf8').split('-- Knowledge work: same repeatable guards as the upgrade migration.')[0];schema=schema.replace(/^  private_draft_owner_id TEXT,\r?\n/m,'').replace(/^  document_metadata TEXT NOT NULL DEFAULT .*\r?\n/gm,'').replace(/^  title TEXT NOT NULL DEFAULT '',\r?\n/m,'');old.exec(schema);expect(old.prepare('PRAGMA table_info(kb_pages)').all().some(c=>c.name==='private_draft_owner_id')).toBe(false);
    old.exec("INSERT INTO workspaces(id,name) VALUES('legacy','Legacy'); INSERT INTO kb_pages(workspace_id,id,title,body,created_by,updated_by) VALUES('legacy','old-page','Old page','Preserved body','old-member','old-member');");const applied=[];const deps={queryRows:async sql=>old.prepare(sql).all(),applyFile:async name=>{applied.push(name);old.exec(fs.readFileSync(new URL('../../worker/migrate/'+name,import.meta.url),'utf8'));}};await applyPostTenantSchemaUpgrades(deps);await applyPostTenantSchemaUpgrades(deps);expect(applied.filter(x=>x==='knowledge-work-alters.sql')).toHaveLength(1);expect(old.prepare("SELECT body,private_draft_owner_id FROM kb_pages WHERE id='old-page'").get()).toMatchObject({body:'Preserved body',private_draft_owner_id:null});
  }finally{old.close();}
 });
 it('Jira transaction refuses linked task evidence before child delete',async()=>{db.exec("INSERT INTO tasks(workspace_id,id,task_key,title,project_id,status_id,creator_id) VALUES('a','task','P-1','Synthetic','p','todo','member'); INSERT INTO task_specs(workspace_id,id,task_id,requirement) VALUES('a','spec','task','Requirement');");const item=(await query({operation:'search',query:'Synthetic',types:['task'],projectIds:[],effectiveOnly:false,cursor:0})).items[0];await executeKnowledgeWork(env,auth(),command('link_source',{pageId:'guide',expectedVersion:1,source:{kind:item.kind,id:item.id,version:item.version}}));expect(()=>{db.exec('BEGIN');try{db.exec("INSERT INTO task_planning_import_guard(workspace_id) VALUES('a'); DELETE FROM tasks WHERE workspace_id='a'; COMMIT;");}catch(e){db.exec('ROLLBACK');throw e;}}).toThrow('knowledge_requires_server_restore');expect(db.prepare("SELECT count(*) n FROM tasks WHERE id='task'").get().n).toBe(1);});
 it('replacement atomically supersedes the predecessor with a frozen page revision and rejects stale retries',async()=>{
  const set=(id,v)=>command('set_metadata',{pageId:id,expectedVersion:v,metadata:{documentKind:'specification',ownerId:'member',applicability:{productVersion:null,environment:null,summary:null}}});
  let first=await executeKnowledgeWork(env,auth(),set('guide',1));first=await executeKnowledgeWork(env,auth(),command('publish',{pageId:'guide',expectedVersion:first.page.pageVersion,expectedPublicationId:null,confirmed:true}));
  db.exec("INSERT INTO kb_pages(workspace_id,id,title,body,created_by,updated_by,project_id) VALUES('a','replacement','Replacement','New body','member','member','p')");let next=await executeKnowledgeWork(env,auth(),set('replacement',1));
  const fields={pageId:'replacement',expectedVersion:next.page.pageVersion,expectedPublicationId:null,predecessorPublicationId:first.page.publication.id,expectedPredecessorVersion:first.page.publication.version,confirmed:true};
  next=await executeKnowledgeWork(env,auth(),command('replace',fields));const old=await query({operation:'publication',publicationId:first.page.publication.id});expect(old.state).toBe('superseded');expect(old.successor_id).toBe(next.page.publication.id);expect(next.page.publication.predecessor_id).toBe(old.id);await expect(executeKnowledgeWork(env,auth(),command('replace',fields))).rejects.toThrow('knowledge_conflict');
 });
 it('a source changed after preview cannot be silently copied into a saved draft',async()=>{const item=(await query({operation:'search',query:'guide',types:['knowledge'],projectIds:[],effectiveOnly:false,cursor:0})).items[0];const p=await query({operation:'prepare_draft',input:{kind:'meeting',notes:'',sourceRefs:[{kind:item.kind,id:item.id,version:item.version}]}});db.prepare('UPDATE kb_pages SET body=?,version=version+1 WHERE id=?').run('Changed privately','guide');await expect(executeKnowledgeWork(env,auth(),command('save_draft',{preview:p,title:'Draft',text:p.text,confirmed:true}))).rejects.toThrow(/knowledge_(conflict|source_unavailable)/);expect(db.prepare('SELECT count(*) n FROM kb_work_receipts').get().n).toBe(0);});
 it('referenced working revisions survive pruning even without publication',async()=>{const item=(await query({operation:'search',query:'guide',types:['knowledge'],projectIds:[],effectiveOnly:false,cursor:0})).items[0];const p=await query({operation:'prepare_draft',input:{kind:'meeting',notes:'',sourceRefs:[{kind:item.kind,id:item.id,version:item.version}]}});await executeKnowledgeWork(env,auth(),command('save_draft',{preview:p,title:'Draft',text:p.text,confirmed:true}));for(let i=0;i<25;i++)db.prepare('UPDATE kb_pages SET body=?,version=version+1 WHERE id=?').run('New '+i,'guide');expect(db.prepare("SELECT count(*) n FROM kb_revisions WHERE page_id='guide' AND version=1").get().n).toBe(1);});
 it('rejects caller identity and missing explicit confirmation in shared core',()=>{expect(()=>parseKnowledgeWorkCommand({commandId:'invalid-command',operation:'publish',pageId:'guide',expectedVersion:1,expectedPublicationId:null,confirmed:false})).toThrow();expect(()=>parseKnowledgeWorkCommand({commandId:'invalid-command',operation:'set_metadata',pageId:'guide',expectedVersion:1,actorId:'admin',metadata:{documentKind:null,ownerId:null,applicability:{productVersion:null,environment:null,summary:null}}})).toThrow();});
});
