// @vitest-environment node
import {beforeEach,afterEach,describe,it,expect} from 'vitest';
import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {Worker} from 'node:worker_threads';
import {executeQaAction} from '../../worker/src/qa.ts';
import {applyPostTenantSchemaUpgrades} from '../../worker/migrate/schema-upgrades.mjs';
const {assertQaCoordinationImportSafe}=await import('../../worker/migrate/qa-coordination-import-guard.mjs');
let db,env,dir,file,serial=0,beforeBatch;const actor=(id='admin',ws='a')=>({userId:id,email:id+'@example.test',member:{id,name:id,role:id==='super'?'super_admin':id==='admin'?'admin':'member',email:id+'@example.test',workspaceId:ws}});
const api=(body,id='admin',ws='a')=>executeQaAction(env,actor(id,ws),body,{waitUntil:p=>p.catch(()=>{})});
const config=(coordinatorId='coordinator',expectedVersion=0,id='admin',commandId='config-'+(++serial))=>api({action:'save_coordination',projectId:'p',coordinatorId,expectedVersion,commandId},id);
const create=async()=>api({action:'create',id:'issue',commandId:'create-'+(++serial),input:{projectId:'p',title:'Synthetic issue',actual:'Example',observedEnvironment:'Stage'}},'reporter');
const command=(issue,value,id='coordinator',cid='command-'+(++serial))=>api({action:'command',id:issue.id,expectedVersion:issue.version,commandId:cid,command:value},id);
const request={type:'request_handoff',reason:'Need a decision',nextOwnerId:'next',replyBy:'2026-10-05T10:00:00.000Z',externalDependency:'External dependency'};
const rows=sql=>db.prepare(sql).all();
// Bootstrap the real schema atomically; avoid a disk sync for every DDL statement. Test writes retain their original transactions.
beforeEach(()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),'livo-qa-coordination-'));file=path.join(dir,'test.sqlite');db=new DatabaseSync(file);db.exec('BEGIN;');try{db.exec(fs.readFileSync(new URL('../../worker/schema.sql',import.meta.url),'utf8'));db.exec('COMMIT;');}catch(error){db.exec('ROLLBACK;');throw error;}db.exec(`PRAGMA journal_mode=WAL;
 INSERT INTO workspaces(id,name) VALUES('a','Synthetic A'),('b','Synthetic B');
 INSERT INTO product_lines(workspace_id,id,name) VALUES('a','line','Line'),('b','line-b','Line');
 INSERT INTO projects(workspace_id,id,line_id,name,key) VALUES('a','p','line','Project','P'),('a','other-p','line','Other','O'),('b','foreign-p','line-b','Foreign','F');
 INSERT INTO system_settings(workspace_id,key,value) VALUES('a','feature_toggles','{"qa":true}'),('b','feature_toggles','{"qa":true}');`);
 for(const id of ['admin','super','coordinator','reporter','rd','qa','next','foreign']){const ws=id==='foreign'?'b':'a';db.prepare('INSERT INTO auth_users(id,email) VALUES(?,?)').run(id,id+'@example.test');db.prepare('INSERT INTO members(workspace_id,id,name,avatar,email,role,auth_id) VALUES(?,?,?,?,?,?,?)').run(ws,id,id,'',id+'@example.test',actor(id).member.role,id);}
 beforeBatch=null;class Statement{constructor(sql,args=[]){this.sql=sql;this.args=args;}bind(...args){return new Statement(this.sql,args);}async first(){return db.prepare(this.sql).get(...this.args)??null;}async all(){return {results:db.prepare(this.sql).all(...this.args),success:true};}async run(){return {success:true,meta:db.prepare(this.sql).run(...this.args)};}execute(){return {results:db.prepare(this.sql).all(...this.args),success:true};}}
 env={DB:{prepare:sql=>new Statement(sql),batch:async statements=>{if(beforeBatch){const fn=beforeBatch;beforeBatch=null;fn();}db.exec('BEGIN IMMEDIATE');try{const results=statements.map(s=>s.execute());db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}},REALTIME:{idFromName:n=>n,get:()=>({fetch:async()=>new Response('ok')})}};
});afterEach(()=>{db.close();if(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(dir).startsWith('livo-qa-coordination-'))fs.rmSync(dir,{recursive:true,force:true});});
describe('QA coordination native SQLite + real Worker adapter',()=>{
 it('admin and super can configure; member cannot',async()=>{await expect(config('coordinator',0,'coordinator')).rejects.toThrow('qa_forbidden');expect(await config()).toMatchObject({coordinatorId:'coordinator',version:1});expect(await config(null,1,'super')).toMatchObject({coordinatorId:null,version:2});});
 it('settings lost-response retry is exactly once; changed body cannot reuse id',async()=>{const body={action:'save_coordination',projectId:'p',coordinatorId:'coordinator',expectedVersion:0,commandId:'same-settings'};const result=await api(body);expect(await api(body)).toEqual(result);await expect(api({...body,coordinatorId:'qa'})).rejects.toThrow('qa_command_id_reused');expect(rows('SELECT * FROM qa_coordination_commands')).toHaveLength(1);});
 it('settings CAS rejects stale version without changing current appointment',async()=>{await config();await expect(config('qa',0)).rejects.toThrow('qa_version_conflict');expect((await api({action:'get_coordination',projectId:'p'})).coordinatorId).toBe('coordinator');});
 it('rejects another workspace owner and inactive appointee',async()=>{await expect(config('foreign')).rejects.toThrow('qa_member_unavailable');db.exec("UPDATE members SET is_active=0 WHERE id='qa'");await expect(config('qa')).rejects.toThrow('qa_member_unavailable');});
 it('archiving or admin demotion after TS preflight is checked in batch',async()=>{beforeBatch=()=>db.exec("UPDATE members SET role='member' WHERE id='admin'");await expect(config()).rejects.toThrow('qa_forbidden');expect(rows('SELECT * FROM qa_coordination_commands')).toHaveLength(0);});
 it('archived project rejects settings commit',async()=>{beforeBatch=()=>db.exec("UPDATE projects SET is_archived=1 WHERE id='p'");await expect(config()).rejects.toThrow('qa_project_unavailable');});
 it('configured coordinator receives one new-report notification',async()=>{await config();await create();expect(rows("SELECT * FROM notifications WHERE recipient_id='coordinator'")).toHaveLength(1);});
 it('new settings never grant PASS or close to coordinator',async()=>{await config();let i=await create();i=await command(i,{type:'triage',assigneeId:'rd',qaOwnerId:'qa',severity:'high',priority:2,dueDate:null});expect(i.state).toBe('triaged');await expect(command(i,{type:'close',resolution:'not_bug',reason:'test'})).rejects.toThrow('qa_forbidden');});
 it('handoff retains owner/state/fixCycle and only next member accepts',async()=>{await config();const i=await command(await create(),request);expect(i).toMatchObject({state:'new',assigneeId:null,qaOwnerId:null,fixCycle:0});await expect(command(i,{type:'accept_handoff',handoffId:i.handoff.id},'admin')).rejects.toThrow('qa_forbidden');const a=await command(i,{type:'accept_handoff',handoffId:i.handoff.id},'next');expect(a.handoff.acceptedBy).toBe('next');});
 it('resolve evidence commits atomically and cannot imply PASS',async()=>{await config();const i=await command(await create(),request);await expect(command(i,{type:'resolve_handoff',handoffId:i.handoff.id,evidence:''},'next')).rejects.toThrow('qa_required');const a=await command(i,{type:'resolve_handoff',handoffId:i.handoff.id,evidence:'Decision recorded'},'next');expect(a.state).toBe('new');expect(a.handoff.resolutionEvidence).toBe('Decision recorded');});
 it('handoff retries have one event, receipt and receiver notification',async()=>{await config();const i=await create(),a=await command(i,request,'coordinator','handoff-once');expect(await command(i,request,'coordinator','handoff-once')).toEqual(a);expect(rows("SELECT * FROM qa_events WHERE type='request_handoff'")).toHaveLength(1);expect(rows("SELECT * FROM notifications WHERE recipient_id='next'")).toHaveLength(1);});
 it('coordinator revocation after domain validation fails inside SQL batch',async()=>{await config();const i=await create();beforeBatch=()=>db.exec("UPDATE qa_project_coordination SET coordinator_id=NULL WHERE id='p'");await expect(command(i,request)).rejects.toThrow('qa_forbidden');expect(rows("SELECT * FROM qa_events WHERE type='request_handoff'")).toHaveLength(0);});
 it('active member/auth identity must remain same at commit',async()=>{await config();const i=await create();beforeBatch=()=>db.exec("UPDATE members SET auth_id='other-auth' WHERE id='coordinator'");await expect(command(i,request)).rejects.toThrow('qa_forbidden');});
 it('banned auth account after preflight cannot commit',async()=>{await config();const i=await create();beforeBatch=()=>db.exec("UPDATE auth_users SET banned=1 WHERE id='coordinator'");await expect(command(i,request)).rejects.toThrow('qa_forbidden');});
 it('archived issues remain readable while mutations stay blocked',async()=>{const i=await create();db.exec("UPDATE projects SET is_archived=1 WHERE id='p'");expect((await api({action:'get',id:i.id},'reporter')).issue.id).toBe(i.id);await expect(command(i,{type:'hold',reason:'x'},'reporter')).rejects.toThrow();});
 it('Jira preflight refuses linked QA before deleting children',async()=>{const i=await create();db.prepare("UPDATE qa_issues SET data=json_set(data,'$.taskIds',json('[\"old-task\"]')) WHERE id=?").run(i.id);expect(()=>db.exec("INSERT INTO task_planning_import_guard(workspace_id) VALUES('a')")).toThrow('qa_task_links_require_restore');expect(rows('SELECT * FROM qa_issues')).toHaveLength(1);});
 it('foreign tenant cannot retrieve or alter coordination',async()=>{await expect(api({action:'get_coordination',projectId:'p'},'foreign','b')).rejects.toThrow('qa_project_unavailable');});
 it('history backup guard rejects unsupported lossy migration',()=>{for(const name of ['qa_project_coordination','qa_coordination_commands'])expect(()=>assertQaCoordinationImportSafe(t=>t===name?[{}]:[])).toThrow('qa_coordination_history_requires_restore');expect(()=>assertQaCoordinationImportSafe(t=>t==='qa_issues'?[{data:{handoff:{id:'h'}}}]:[])).toThrow('qa_coordination_history_requires_restore');expect(()=>assertQaCoordinationImportSafe(()=>[])).not.toThrow();});
 it('real upgrade probes install the missing legacy auth column once across two runs',async()=>{
  const issue=await create();const before=JSON.stringify(rows('SELECT data FROM qa_issues'));
  db.exec('DROP TRIGGER qa_command_coordination_guard;ALTER TABLE qa_commands DROP COLUMN actor_auth_id;DROP TABLE qa_coordination_commands;DROP TABLE qa_project_coordination;');
  let alters=0;for(let n=0;n<2;n++)await applyPostTenantSchemaUpgrades({queryRows:async sql=>rows(sql),applyFile:async file=>{if(file==='qa-coordination-alters.sql')alters++;db.exec(fs.readFileSync(new URL('../../worker/migrate/'+file,import.meta.url),'utf8'));}});
  expect(alters).toBe(1);expect(JSON.stringify(rows('SELECT data FROM qa_issues'))).toBe(before);expect(rows('SELECT actor_auth_id FROM qa_commands')[0].actor_auth_id).toBeNull();
  expect((await command(issue,{type:'hold',reason:'Still tracked'},'reporter')).holdReason).toBe('Still tracked');
 });
 it('reapplies real coordination migration twice without dropping current history',async()=>{await config();await command(await create(),request);const before=JSON.stringify(rows('SELECT * FROM qa_events'));for(let n=0;n<2;n++)db.exec(fs.readFileSync(new URL('../../worker/migrate/qa-coordination.sql',import.meta.url),'utf8'));expect(JSON.stringify(rows('SELECT * FROM qa_events'))).toBe(before);expect((await api({action:'get_coordination',projectId:'p'})).version).toBe(1);});
 it('restoring handoff history permits an existing inactive historical receiver',async()=>{await config();await command(await create(),request);db.exec("UPDATE members SET is_active=0 WHERE id='next'");const r=await api({action:'restore',tables:{qa_issues:rows('SELECT * FROM qa_issues')},validateOnly:true},'super');expect(r.skipped).toBe(1);expect(r.conflicts).toEqual([]);});
 it('settings restore preserves rather than silently omits optional new tables',async()=>{await config();const tables={qa_project_coordination:rows('SELECT workspace_id,id,coordinator_id,version,updated_by,updated_at FROM qa_project_coordination'),qa_coordination_commands:rows('SELECT workspace_id,id,project_id,actor_id,actor_auth_id,payload_hash,expected_version,response,created_at FROM qa_coordination_commands')};db.exec("UPDATE projects SET is_archived=1 WHERE id='p'");const r=await api({action:'restore',tables,validateOnly:true},'super');expect(r.skipped).toBe(2);expect(r.conflicts).toEqual([]);});
 it('two SQLite writers use config CAS; exactly one succeeds',async()=>{
  const workerCode=`const {parentPort,workerData}=require('node:worker_threads');const {DatabaseSync}=require('node:sqlite');const db=new DatabaseSync(workerData.file);db.exec('PRAGMA busy_timeout=3000');try{db.exec('BEGIN IMMEDIATE');db.prepare('INSERT INTO qa_coordination_commands(workspace_id,id,project_id,actor_id,actor_auth_id,payload_hash,expected_version,response,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(...workerData.args);db.prepare('INSERT INTO qa_project_coordination(workspace_id,id,coordinator_id,version,updated_by,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(workspace_id,id) DO UPDATE SET coordinator_id=excluded.coordinator_id,version=excluded.version').run('a','p',workerData.owner,1,'admin','now');db.exec('COMMIT');parentPort.postMessage({ok:true,thread:require('node:worker_threads').threadId});}catch(e){try{db.exec('ROLLBACK');}catch{}parentPort.postMessage({ok:false,error:e.message,thread:require('node:worker_threads').threadId});}finally{db.close();}`;
  const writer=(id,owner)=>new Promise((resolve,reject)=>{const worker=new Worker(workerCode,{eval:true,workerData:{file,owner,args:['a',id,'p','admin','admin','hash',0,JSON.stringify({projectId:'p',coordinatorId:owner,version:1}),'now']}});worker.once('message',resolve);worker.once('error',reject);});
  const result=await Promise.all([writer('race-a','coordinator'),writer('race-b','qa')]);expect(new Set(result.map(r=>r.thread)).size).toBe(2);expect(result.filter(r=>r.ok)).toHaveLength(1);expect(result.find(r=>!r.ok).error).toContain('qa_version_conflict');expect(rows('SELECT * FROM qa_coordination_commands')).toHaveLength(1);
 });
});
