-- Optional Docker delivery pipeline. Capture and business writes commit together.
-- Enable only after an administrator sets system_settings.slack_delivery routes.
CREATE TABLE IF NOT EXISTS public.slack_delivery_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key text NOT NULL,
  team_id text NOT NULL,
  task_id text NOT NULL,
  target_type text NOT NULL CHECK (target_type IN ('channel','member')),
  target_id text NOT NULL,
  payload jsonb NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sending','sent','failed','review','skipped')),
  attempts integer NOT NULL DEFAULT 0,
  available_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  lease_owner uuid,
  lease_expires_at timestamptz,
  slack_channel_id text,
  slack_message_ts text,
  last_error text,
  sent_at timestamptz,
  UNIQUE (event_key,team_id,target_type,target_id)
);
CREATE INDEX IF NOT EXISTS slack_delivery_ready ON public.slack_delivery_outbox(status,available_at,id);
CREATE INDEX IF NOT EXISTS slack_delivery_card ON public.slack_delivery_outbox(team_id,task_id,target_type,target_id,status);
ALTER TABLE public.slack_delivery_outbox ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.slack_delivery_outbox FROM anon, authenticated;
GRANT ALL ON public.slack_delivery_outbox TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.slack_delivery_outbox_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.livo_slack_delivery_channels(p_project text)
RETURNS TABLE(channel_id text) LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT DISTINCT r->>'channelId'
  FROM public.system_settings s
  CROSS JOIN LATERAL jsonb_array_elements(CASE WHEN jsonb_typeof(s.value->'routes')='array'
    THEN s.value->'routes' ELSE '[]'::jsonb END) r
  JOIN public.projects p ON p.id=p_project AND NOT p.is_archived
  WHERE s.key='slack_delivery' AND s.value->'enabled'='true'::jsonb
    AND s.value->>'teamId' ~ '^T[A-Z0-9]+$'
    AND r->>'channelId' ~ '^[CG][A-Z0-9]+$'
    AND COALESCE(r->'enabled','true'::jsonb)='true'::jsonb
    AND ((r->>'projectId')=p.id OR (r->>'lineId')=p.line_id)
$$;
REVOKE ALL ON FUNCTION public.livo_slack_delivery_channels(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.livo_slack_delivery_channels(text) TO service_role;

CREATE OR REPLACE FUNCTION public.livo_slack_capture_delivery()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
  cfg jsonb;
  card public.tasks%ROWTYPE;
  project public.projects%ROWTYPE;
  actor text := public.current_member_id();
  actor_name text;
  event_key text;
  kind text;
  changes jsonb := '[]'::jsonb;
  field text;
  label text;
  before_value text;
  after_value text;
  body jsonb;
  source_channel text;
  channel text;
  enabled_types text[];
  event_types text[] := ARRAY[]::text[];
BEGIN
  SELECT value INTO cfg FROM public.system_settings WHERE key='slack_delivery';
  IF cfg->'enabled' IS DISTINCT FROM 'true'::jsonb OR COALESCE(cfg->>'teamId','') !~ '^T[A-Z0-9]+$' THEN RETURN NEW; END IF;
  -- Also permits trusted importers to silence a transaction without a historical backfill.
  IF current_setting('livo.slack_silent',true)='true' THEN RETURN NEW; END IF;
  IF TG_TABLE_NAME='tasks' THEN
    card := NEW;
    IF TG_OP='INSERT' THEN
      kind := 'created'; event_key := 'task:' || NEW.id || ':created';
      actor := COALESCE(actor,NEW.creator_id); event_types := ARRAY['task_created'];
    ELSE
      kind := 'updated'; event_key := 'task:' || NEW.id || ':' || gen_random_uuid()::text;
      FOREACH field IN ARRAY ARRAY['status_id','assignee_id','reviewer_id','priority','due_date','title'] LOOP
        IF to_jsonb(OLD)->field IS NOT DISTINCT FROM to_jsonb(NEW)->field THEN CONTINUE; END IF;
        before_value := to_jsonb(OLD)->>field; after_value := to_jsonb(NEW)->>field;
        label := CASE field WHEN 'status_id' THEN '狀態' WHEN 'assignee_id' THEN '經辦人'
          WHEN 'reviewer_id' THEN '驗收人' WHEN 'priority' THEN '優先級' WHEN 'due_date' THEN '到期日' ELSE '標題' END;
        IF field='status_id' THEN
          SELECT name INTO before_value FROM public.statuses WHERE id=before_value;
          SELECT name INTO after_value FROM public.statuses WHERE id=after_value;
        ELSIF field IN ('assignee_id','reviewer_id') THEN
          SELECT name INTO before_value FROM public.members WHERE id=before_value;
          SELECT name INTO after_value FROM public.members WHERE id=after_value;
        END IF;
        changes := changes || jsonb_build_array(jsonb_build_object('field',field,'label',label,'before',before_value,'after',after_value));
        event_types := array_append(event_types,CASE field WHEN 'status_id' THEN 'status_changed'
          WHEN 'assignee_id' THEN 'assignee_changed' WHEN 'priority' THEN 'priority_changed' ELSE 'task_updated' END);
      END LOOP;
      IF jsonb_array_length(changes)=0 THEN RETURN NEW; END IF;
    END IF;
  ELSE
    SELECT * INTO card FROM public.tasks WHERE id=NEW.task_id;
    IF NOT FOUND THEN RETURN NEW; END IF;
    IF TG_TABLE_NAME='comments' THEN
      kind := 'comment'; actor := NEW.user_id;
      event_key := 'comment:' || NEW.id; event_types := ARRAY['comment_added'];
      IF NEW.source='slack' AND public.livo_slack_session() THEN
        source_channel := auth.jwt()->'livo_slack_source'->>'channel';
      END IF;
    ELSE
      IF cfg->'dmEnabled' IS DISTINCT FROM 'true'::jsonb OR NEW.recipient_id=NEW.sender_id THEN RETURN NEW; END IF;
      kind := 'personal'; actor := NEW.sender_id; event_key := 'notification:' || NEW.id;
    END IF;
  END IF;
  SELECT * INTO project FROM public.projects WHERE id=card.project_id AND NOT is_archived;
  IF NOT FOUND OR NOT EXISTS(SELECT 1 FROM public.livo_slack_delivery_channels(card.project_id)) THEN RETURN NEW; END IF;
  SELECT task_notify_types INTO enabled_types FROM public.backup_settings LIMIT 1;
  enabled_types := COALESCE(enabled_types,ARRAY['task_created','status_changed','assignee_changed','priority_changed','comment_added','task_updated']);
  IF kind<>'personal' AND NOT (event_types && enabled_types) THEN RETURN NEW; END IF;
  SELECT name INTO actor_name FROM public.members WHERE id=actor;
  body := jsonb_build_object('kind',kind,'taskKey',card.task_key,'taskTitle',card.title,
    'projectId',project.id,'lineId',project.line_id,'projectKey',project.key,'projectName',project.name,
    'actorName',COALESCE(actor_name,'系統'),'priority',card.priority,'dueDate',card.due_date,
    'assigneeName',(SELECT name FROM public.members WHERE id=card.assignee_id),
    'changes',changes,'sourceChannelId',source_channel);
  IF kind IN ('comment','personal') THEN body := body || jsonb_build_object('content',left(NEW.content,10000)); END IF;
  IF kind='personal' THEN
    body := body || jsonb_build_object('reason',NEW.type);
    INSERT INTO public.slack_delivery_outbox(event_key,team_id,task_id,target_type,target_id,payload)
      VALUES(event_key,cfg->>'teamId',card.id,'member',NEW.recipient_id,body) ON CONFLICT DO NOTHING;
  ELSE
    FOR channel IN SELECT channel_id FROM public.livo_slack_delivery_channels(card.project_id) LOOP
      IF channel IS NOT DISTINCT FROM source_channel THEN CONTINUE; END IF;
      INSERT INTO public.slack_delivery_outbox(event_key,team_id,task_id,target_type,target_id,payload)
        VALUES(event_key,cfg->>'teamId',card.id,'channel',channel,body) ON CONFLICT DO NOTHING;
    END LOOP;
  END IF;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.livo_slack_capture_delivery() FROM PUBLIC, anon, authenticated;
CREATE OR REPLACE TRIGGER livo_slack_capture_tasks AFTER INSERT OR UPDATE ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.livo_slack_capture_delivery();
CREATE OR REPLACE TRIGGER livo_slack_capture_comments AFTER INSERT ON public.comments
  FOR EACH ROW EXECUTE FUNCTION public.livo_slack_capture_delivery();
CREATE OR REPLACE TRIGGER livo_slack_capture_personal AFTER INSERT ON public.notifications
  FOR EACH ROW EXECUTE FUNCTION public.livo_slack_capture_delivery();

-- One short-lived delivery at a time. Slow or crashed senders cannot create a
-- competing root thread. An expired send is uncertain, so it requires review.
CREATE OR REPLACE FUNCTION public.livo_slack_claim_delivery(p_owner uuid)
RETURNS SETOF public.slack_delivery_outbox LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE job public.slack_delivery_outbox%ROWTYPE;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('livo-slack-delivery'));
  IF NOT EXISTS(SELECT 1 FROM public.system_settings WHERE key='slack_delivery' AND value->'enabled'='true'::jsonb) THEN RETURN; END IF;
  UPDATE public.slack_delivery_outbox SET status='review',last_error='expired_delivery_lease',lease_owner=NULL,lease_expires_at=NULL
    WHERE status='sending' AND lease_expires_at<clock_timestamp();
  IF EXISTS(SELECT 1 FROM public.slack_delivery_outbox WHERE status='sending') THEN RETURN; END IF;
  SELECT q.* INTO job FROM public.slack_delivery_outbox q
    WHERE q.status='pending' AND q.available_at<=clock_timestamp()
    AND NOT EXISTS(SELECT 1 FROM public.slack_delivery_outbox blocked
      WHERE blocked.team_id=q.team_id AND blocked.task_id=q.task_id AND blocked.target_type=q.target_type
      AND blocked.target_id=q.target_id AND (blocked.status='review' OR (blocked.status='pending' AND blocked.id<q.id)))
    ORDER BY q.id FOR UPDATE SKIP LOCKED LIMIT 1;
  IF NOT FOUND THEN RETURN; END IF;
  UPDATE public.slack_delivery_outbox SET status='sending',attempts=attempts+1,lease_owner=p_owner,
    lease_expires_at=clock_timestamp()+interval '120 seconds' WHERE id=job.id RETURNING * INTO job;
  RETURN NEXT job;
END;
$$;
REVOKE ALL ON FUNCTION public.livo_slack_claim_delivery(uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.livo_slack_claim_delivery(uuid) TO service_role;

CREATE OR REPLACE FUNCTION public.livo_slack_finish_delivery(p_id bigint,p_owner uuid,p_status text,
  p_channel text DEFAULT NULL,p_message_ts text DEFAULT NULL,p_thread_ts text DEFAULT NULL,
  p_error text DEFAULT NULL,p_delay_seconds integer DEFAULT 0)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE job public.slack_delivery_outbox%ROWTYPE;
BEGIN
  SELECT * INTO job FROM public.slack_delivery_outbox WHERE id=p_id AND status='sending' AND lease_owner=p_owner
    AND lease_expires_at>clock_timestamp() FOR UPDATE;
  IF NOT FOUND THEN RETURN false; END IF;
  IF p_status NOT IN ('sent','pending','review','failed','skipped') THEN RAISE EXCEPTION 'Invalid delivery result'; END IF;
  IF p_status='sent' THEN
    IF COALESCE(p_channel,'') !~ '^[CDG][A-Z0-9]+$' OR COALESCE(p_message_ts,'') !~ '^[0-9]+\.[0-9]+$'
      OR COALESCE(p_thread_ts,'') !~ '^[0-9]+\.[0-9]+$' THEN RAISE EXCEPTION 'Missing Slack receipt'; END IF;
    IF EXISTS(SELECT 1 FROM public.tasks WHERE id=job.task_id) THEN
      INSERT INTO public.slack_thread_mappings(slack_team_id,slack_channel_id,slack_thread_ts,task_id,notification_type)
        VALUES(job.team_id,p_channel,p_thread_ts,job.task_id,'delivery')
        ON CONFLICT(slack_channel_id,slack_thread_ts) DO NOTHING;
    END IF;
  END IF;
  UPDATE public.slack_delivery_outbox SET status=p_status,slack_channel_id=p_channel,slack_message_ts=p_message_ts,
    last_error=left(p_error,100),available_at=clock_timestamp()+make_interval(secs=>greatest(0,least(p_delay_seconds,86400))),
    sent_at=CASE WHEN p_status='sent' THEN clock_timestamp() END,lease_owner=NULL,lease_expires_at=NULL
    WHERE id=p_id AND lease_owner=p_owner;
  RETURN true;
END;
$$;
REVOKE ALL ON FUNCTION public.livo_slack_finish_delivery(bigint,uuid,text,text,text,text,text,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.livo_slack_finish_delivery(bigint,uuid,text,text,text,text,text,integer) TO service_role;
