import type { Row } from './core.ts';
export function knowledgeLabel(key:string,locale:unknown):string {
  const labels:Record<string,[string,string,string]>={
    unknown:['未指定','未指定','Unspecified'],unlink:['移除參考','移除参考','Remove reference'],saveMetadata:['儲存資料','保存信息','Save metadata'],ownerNote:['負責人空白會保留原設定；清除負責人請至 LIVO。','负责人空白会保留原设置；清除请至 LIVO。','An empty owner keeps the current owner. Use LIVO to clear it.'],incomplete:['來源不完整或表單超過 Slack 大小限制，請在 LIVO 繼續。','来源不完整或表单超出 Slack 大小限制，请在 LIVO 继续。','Sources are incomplete or the form exceeds Slack limits. Continue in LIVO.'],title:['知識與草稿','知识与草稿','Knowledge & drafts'],close:['關閉','关闭','Close'],loading:['正在載入…','正在加载…','Loading…'],saving:['正在儲存…','正在保存…','Saving…'],saved:['已儲存。可在 LIVO 查看；未自動發送訊息。','已保存。可在 LIVO 查看；未自动发送消息。','Saved in LIVO. No message was sent automatically.'],
    unavailable:['操作未完成，請重新開啟。','操作未完成，请重新打开。','Could not complete. Please reopen.'],conflict:['資料已改變，請重新開啟並核對；沒有套用舊資料。','数据已改变，请重新打开并核对；没有应用旧数据。','Data changed. Reopen and review before saving.'],expired:['表單已過期，請重新開啟；尚未儲存。','表单已过期，请重新打开；尚未保存。','This form expired. Reopen it; it was not saved.'],scope:['來源的可見範圍與目的地不相容，草稿保持私人。','来源的可见范围与目标位置不兼容，草稿保持私人。','Source permissions do not permit this destination. The draft remains private.'],
    search:['搜尋規格／任務／QA／檔案','搜索规格／任务／QA／文件','Search specifications, tasks, QA, files'],keyword:['關鍵字','关键词','Search terms'],open:['開啟 LIVO','打开 LIVO','Open LIVO'],preview:['預覽','预览','Preview'],next:['下一頁','下一页','Next'],previous:['上一頁','上一页','Previous'],empty:['目前沒有可見結果。','当前没有可见结果。','No visible results.'],
    metadata:['規格／決策資料','规格／决策信息','Specification / decision'],kind:['文件性質','文档类型','Document type'],specification:['規格','规格','Specification'],decision:['決策','决策','Decision'],owner:['負責人','负责人','Owner'],productVersion:['適用產品版本','适用产品版本','Applicable product version'],environment:['適用環境','适用环境','Applicable environment'],summary:['適用範圍說明','适用范围说明','Applicability notes'],publish:['確認為有效版本','确认为有效版本','Publish effective version'],replace:['取代其他有效版本','替代其他有效版本','Replace another effective version'],predecessor:['被取代的有效文件','被替代的有效文档','Effective document being replaced'],link:['連結參考來源','关联参考来源','Link a source'],
    meeting:['會議草稿','会议草稿','Meeting draft'],weekly:['週報草稿','周报草稿','Weekly draft'],draftTitle:['草稿標題','草稿标题','Draft title'],notes:['筆記／補充內容','笔记／补充内容','Notes / additional context'],sources:['參考來源（最多 3 個）','参考来源（最多 3 个）','Sources (up to 3)'],from:['期間開始','期间开始','Period start'],to:['期間結束','期间结束','Period end'],prepare:['產生預覽','生成预览','Prepare preview'],save:['儲存私人草稿','保存私人草稿','Save private draft'],share:['分享至工作頁面','分享到工作页面','Share to workspace'],destination:['目的地父頁面（空白為團隊根目錄）','目标父页面（空白为团队根目录）','Parent page (empty = team root)'],confirm:['我已核對，確認執行本次操作','我已核对，确认执行本次操作','I reviewed this and confirm this action'],confirmNeeded:['請明確勾選確認。','请明确勾选确认。','Please confirm explicitly.'],retry:['重試同一個操作','重试同一操作','Retry the same operation'],
    previewNote:['完整預覽如下。尚未儲存、分享或定案；儲存後仍是本人私人草稿。僅涵蓋選定來源，檔案只含檔名。','完整预览如下。尚未保存、分享或定案；保存后仍为本人私人草稿。仅涵盖选定来源，文件只含文件名。','Complete preview below. Not saved, shared, or approved. Saving creates an owner-only draft. Only selected sources are included; files contribute metadata only.'],
    publishNote:['這會固定目前版本為有效依據；後續正文編輯不會自動變更有效版本。','这会固定当前版本为有效依据；之后正文编辑不会自动变更有效版本。','This pins the current version as effective. Later edits do not automatically change it.'],shareNote:['這會依目的地既有權限分享給可見成員；不會自動發送 Slack。私人來源限制仍會核對。','这会按目标位置现有权限分享给可见成员；不会自动发送 Slack。仍会核对私人来源限制。','Share under the destination permissions. No Slack message is sent. Private source restrictions still apply.'],partial:['此處是部分正文預覽；請開啟 LIVO 閱讀完整內容。','此处为部分正文预览；请打开 LIVO 阅读全文。','Partial preview; open LIVO for the complete body.'],
  };
  const code=String(locale||'').toLowerCase(),i=code.startsWith('en')?2:code.includes('cn')||code==='zh-hans'?1:0;
  return labels[key]?.[i] || labels.unavailable[i];
}
export const knowledgePlain=(text:string):Row=>({type:'section',text:{type:'plain_text',text:text.slice(0,3000)||'—'}});
export const knowledgeButton=(id:string,label:string,value:Row={}):Row=>({type:'button',action_id:id,text:{type:'plain_text',text:label.slice(0,75)},value:JSON.stringify(value)});
export function knowledgeModal(blocks:Row[],source:Row,callback='livo_knowledge_work',submit?:string):Row {
 return {type:'modal',callback_id:callback,private_metadata:JSON.stringify(source),title:{type:'plain_text',text:knowledgeLabel('title',source.locale)},close:{type:'plain_text',text:knowledgeLabel('close',source.locale)},...(submit?{submit:{type:'plain_text',text:submit.slice(0,24)}}:{}),blocks};
}
export const knowledgeInput=(id:string,label:string,element:Row,optional=false):Row=>({type:'input',block_id:id,optional,label:{type:'plain_text',text:label},element:{action_id:id,...element}});
export const knowledgeConfirm=(locale:unknown):Row=>knowledgeInput('confirm',knowledgeLabel('confirm',locale),{type:'checkboxes',options:[{text:{type:'plain_text',text:knowledgeLabel('confirm',locale)},value:'yes'}]});
export function knowledgeNotice(key:string,source:Row,retry=false):Row {
 const mapped=key==='knowledge_conflict'?'conflict':key==='knowledge_scope_conflict'?'scope':key.startsWith('knowledge_')?'unavailable':key;
 return knowledgeModal([knowledgePlain(knowledgeLabel(mapped,source.locale)),...(retry?[{type:'actions',elements:[knowledgeButton('livo_kw_retry',knowledgeLabel('retry',source.locale))]}]:[])],source);
}
